In [47]:
import pandas as pd

xls = pd.ExcelFile(r'C:\Users\svi02\Documents\misc\erfp_green.xls')
sheet_name = xls.sheet_names
sheet_name

['Grid Results 1',
 'Grid Results 2',
 'Grid Results 3',
 'Grid Results 4',
 'Grid Results 5',
 'Grid Results 6',
 'Grid Results 7',
 'Grid Results 8',
 'Grid Results 9',
 'Grid Results 10']

In [48]:
df=pd.read_excel(filename,
              sheet_name=None, 
              encoding='utf-8')

In [49]:
df.keys()

odict_keys(['Grid Results 1', 'Grid Results 2', 'Grid Results 3', 'Grid Results 4', 'Grid Results 5', 'Grid Results 6', 'Grid Results 7', 'Grid Results 8', 'Grid Results 9', 'Grid Results 10'])

In [50]:
df = pd.concat(df[frame] for frame in df.keys())
df.shape

(622579, 2)

In [51]:
df_na = df.dropna(axis = 0, how ='any')

In [112]:
df_new = df_na[df_na['STRING_VALUE'].str.contains('[\w]')]

In [113]:
df_new

                                            STRING_VALUE  count(*)
0                                                      Y   1289404
1                                                      N    938529
4                                                    Yes    220301
5                                                      0    217701
6                                                      B    175165
7                                                     No    129546
8                                          00:00 - 23:59     80640
10                                                     F     67130
11                                                    RT     60625
12                                           00:00-23:59     54009
13                                                    YX     51188
14                                                    HI     51093
15                                                     1     48087
16                                                     D     47686
17                                                   6PM     38074
18                                                    WV     35182
20                                         00:00 - 00:00     29131
21                                           Parking lot     28794
22                                              24 Hours     25944
23                                                    HY     21517
24                                                     L     21089
25                                                    KM     20379
26                                                    BW     18614
27                                                     C     18324
28                                                    SI     18285
29                                                     p     17262
30                                                    UI     17225
31                                                    SM     16921
32                                                    86     16713
33                                                    HL     16691
...                                                  ...       ...
32734                                            \t42075         1
32735                                         \t41216464         1
32736                                            \t40083         1
32737                                             \t3858         1
32738                                             \t3594         1
32739                                             \t3353         1
32740                                            \t32288         1
32741                                            \t31763         1
32742                                           \t309495         1
32743                                            \t28429         1
32744                                             \t2484         1
32745                                             \t2443         1
32746                                             \t2044         1
32747                                           \t201339         1
32748                                            \t16260         1
32749                                            \t15280         1
32750                                            \t13939         1
32751                                           \t135114         1
32752                                            \t11968         1
32753  \t08-04 (Level-8), Union Financial Centre, Cor...         1
32754                                      \t06:00-23:00         1
32755                                      \t00:00-24:00         1
32756                                    \t00:00 - 23:59         1
32757                           \t reservas@hotelluz.com         1
32758                   \t reservas@hotelcaminoplaza.com         1
32759                   \t office.hotel.urania@gmail.com         1
32760                   \t info@hotel-zur-post-hameln.de         1
32761                                             \t  60         1
32762  Larger room than standard room\nOne-way airpo...         1
32763          Internet\n Parking\n Gym\n Min. water         1

[622469 rows x 2 columns]

In [98]:
df_new[df_new.count_number >= 6]

                                           string_value  count_number
0                                                     Y       1289404
1                                                     N        938529
4                                                   Yes        220301
6                                                     B        175165
7                                                    No        129546
8                                         00:00 - 23:59         80640
10                                                    F         67130
11                                                   RT         60625
12                                          00:00-23:59         54009
13                                                   YX         51188
14                                                   HI         51093
16                                                    D         47686
17                                                  6PM         38074
18                                                   WV         35182
19                                                    -         33280
20                                        00:00 - 00:00         29131
21                                          Parking lot         28794
22                                             24 Hours         25944
23                                                   HY         21517
24                                                    L         21089
25                                                   KM         20379
26                                                   BW         18614
27                                                    C         18324
28                                                   SI         18285
29                                                    p         17262
30                                                   UI         17225
31                                                   SM         16921
33                                                   HL         16691
34                                                   CP         16368
36                                                   MC         15656
...                                                 ...           ...
8022                                            .5 Mile             6
8023                                           .2 miles             6
8024                                                 -0             6
8025                                           --None--             6
8026                                               +973             6
8027                                                +94             6
8028                                     +91-9911701701             6
8029                                   +86 10 6584 6000             6
8030                                                +81             6
8031                                   +55 11 3059-3277             6
8032                                               +380             6
8033                                               +255             6
8034                                                ***             6
8035                                              (0)89             6
8036                                              $8.00             6
8037                                                $60             6
8038                                             $40.00             6
8039                                                $14             6
8040                                               $100             6
8041  $10 Credit to "Raid the Bar" with Kimpton Karm...             6
8043                                              "N/A"             6
8044                                            露天停车场,              6
8045                                              公共停车场             6
8046                                    マイステイズホテルマネジメント             6
8047                                               Taxi             6
8048                                      LEED programs             6
8049                    Larger room than standard room              6
8050                       BTG-JIANGUO Hotels & Resorts             6
8051                                                  3             6
8052                                                24h             6

[43005 rows x 2 columns]

In [105]:
df_new.to_excel(r'C:\Users\svi02\Documents\misc\green_hotels_clean.xlsx')