In [7]:
import requests
import json
import pandas as pd
final_df = pd.DataFrame()
url = "https://api.hotel-audit.hrs.com/v1/audits/auth/login"
response = requests.post(url, data={"client_id": "00000000-0000-0000-0000-000000000000", "client_secret": "00000000-0000-0000-0000-000000000000"})
data = response.text
response
# parsed = json.loads(data)
# df = pd.DataFrame(parsed.get('results'))
# final_df = final_df.append(df)

In [16]:
url = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=2&size=100"
response = requests.get(url)
data = response.text
parsed = json.loads(data)
df1 = pd.DataFrame(parsed.get('results'))
df1

,id,hkey,name,created_date,updated_date,checked,link,program_name,version,terms,...,chain_name,brand_id,brand_name,city_id,city,country_id,country,performance_cluster,status,type
0,04a6d881-fd68-42b9-810a-98b635169eb9,22415.0,Novum City Apart,2020-07-08T15:45:12.000Z,2020-07-08T15:45:12.000Z,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,32,33,3...",https://www.novum-hotels.com/hilfe,Novum Help Center,1,2,...,Novum Hotels,1733.0,Novum Hotels,107905.0,Hamburg (Hamburg),33.0,Germany,3.0,True,cleansafe_self_inspection
1,04acd365-ec60-4fcb-a158-cbd6e862806c,147070.0,Best Western Park Hotel & Resort,2020-07-14T12:43:05.000Z,2020-07-14T12:43:05.000Z,"1,2,3,4,5,6,7,8,10,11,12,14,15,16,17,18,19,27,...",https://www.bestwestern.it/hotels/specialprote...,BEST WESTERN SPECIAL PROTECTION,1,2,...,Best Western,60.0,Best Western,553601.0,Fiano Romano (Lazio),65.0,Italy,2.0,True,cleansafe_self_inspection
2,04aeac5f-d5a6-453f-8991-c6da08a4a084,407722.0,Hotel 525,2020-07-02T10:44:20.000Z,2020-07-02T10:44:20.000Z,"1,2,3,4,5,6,7,8,10,11,12,14,15,16,17,18,19,20,...",https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,individual,-1.0,n.a.,172717.0,Los Alcázares (Región de Murcia),140.0,Spain,5.0,False,cleansafe_self_inspection
3,04b10aa0-1fcd-4574-8655-49fd48406ebf,62044.0,Palacio del Mar,2020-07-17T12:47:54.000Z,2020-07-17T12:47:54.000Z,None,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,Sercotel,340.0,Sercotel,64569.0,Santander (Cantabria),140.0,Spain,NaN,False,cleansafe_self_inspection
4,04b5cd82-ff84-434e-a88a-9e5a3321f33e,NaN,None,2020-07-13T09:30:19.000Z,2020-07-13T09:30:19.000Z,"1,2,3,4,5,6,7,8,10,11,12,9,14,15,16,17,18,19,2...",https://www.relexa-hotel-muenchen.de/hotel/ser...,relexa corona etikette,1,2,...,None,NaN,None,NaN,None,NaN,None,NaN,True,cleansafe_self_inspection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,095bcc83-c790-4d3f-869f-ff3087e798f9,422808.0,Villa le Maschere | UNA Esperienze,2020-07-06T09:19:03.000Z,2020-07-06T09:19:03.000Z,None,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,Una Hotels,447.0,Una Hotels,210238.0,Barberino di Mugello (Toscana),65.0,Italy,5.0,False,cleansafe_self_inspection
96,09731713-73d3-46fe-b9cb-d158fb9234b2,10074.0,An der Oper,2020-07-08T15:45:12.000Z,2020-07-08T15:45:12.000Z,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,32,33,3...",https://www.novum-hotels.com/hilfe,Novum Help Center,1,2,...,Novum Hotels,1733.0,Novum Hotels,97205.0,Düsseldorf (Nordrhein-Westfalen),33.0,Germany,3.0,True,cleansafe_self_inspection
97,0974fa90-7062-47c0-8d27-f8c8d4e8deab,37782.0,Zumnorde am Anger,2020-06-21T09:45:30.000Z,2020-06-21T09:45:30.000Z,"1,2,3,4,5,6,8,10,11,12,9,13,14,15,16,17,18,19,...",https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,individual,-1.0,n.a.,60118.0,Erfurt (Thüringen),33.0,Germany,2.0,True,cleansafe_self_inspection
98,098828c2-2df6-4aa4-a9c8-8a86002d1121,699338.0,IBB Blue Hotel Adlershof Berlin-Airport,2020-07-17T11:33:48.000Z,2020-07-17T11:33:48.000Z,"1,2,3,4,5,6,10,11,9,13,14,15,16,17,18,19,29,30...",https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,IBB Hotels,946.0,IBB Hotels,55133.0,Berlin (Berlin),33.0,Germany,2.0,False,cleansafe_self_inspection
99,09a15ec8-a35c-4c01-a21e-f4ab7f1823cb,454173.0,Aurora,2020-07-17T06:59:09.000Z,2020-07-17T06:59:09.000Z,"1,2,3,4,5,6,7,8,10,11,12,9,14,15,16,17,18,19,2...",https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,individual,-1.0,n.a.,4581.0,Castione della Presolana (Lombardia),65.0,Italy,NaN,False,cleansafe_self_inspection

In [20]:
df = df.append(df1, ignore_index=True)
df

(200, 24)

In [7]:
print(json.dumps(parsed, indent=4))

{
    "results": [
        {
            "id": "0012e88e-c7d3-43f7-a406-efd7ee8a9612",
            "hkey": 153403,
            "name": "Louisa's Place",
            "created_date": "2020-06-18T10:08:36.000Z",
            "updated_date": "2020-06-18T10:08:36.000Z",
            "checked": "3,6,8,10,12,14,15,16,17,18,19,24,25,26,27,29,30,31,34,35,36,37,38,39,41,42",
            "link": "https://travail-emploi.gouv.fr/IMG/pdf/protocole-deconfinement-covid-19-hcr.pdf",
            "program_name": "Protocole de d\u00e9confinement commun \u00e0 toute la profession HCR",
            "version": 1,
            "terms": 1,
            "services": "breakfast,restaurant,fitness",
            "audit_date": null,
            "auditor": null,
            "chain_id": -1,
            "chain_name": "individual",
            "brand_id": -1,
            "brand_name": "n.a.",
            "city_id": 55133,
            "city": "Berlin (Berlin)",
            "country_id": 33,
            "country": "Germany",
            "performance_cluster": 2,
            "status": false,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "0026579c-66c4-4845-b280-d7435ec627b8",
            "hkey": 260487,
            "name": "Castle Arch",
            "created_date": "2020-07-17T12:47:52.000Z",
            "updated_date": "2020-07-17T12:47:52.000Z",
            "checked": "1,2,3,4,5,6,8,10,11,12,9,14,15,16,17,18,19,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46",
            "link": "https://www.castlearchhotel.com/stay-safe-at-the-castle-arch-hotel.html",
            "program_name": "Failte Ireland Covid 19 Safety charter",
            "version": 1,
            "terms": 2,
            "services": "breakfast,restaurant,mice",
            "audit_date": null,
            "auditor": null,
            "chain_id": 1988,
            "chain_name": "Magnuson Group",
            "brand_id": 1988,
            "brand_name": "Magnuson Group",
            "city_id": 3070924,
            "city": "Meath (Meath)",
            "country_id": 62,
            "country": "Ireland",
            "performance_cluster": 5,
            "status": true,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "002fed63-5e6e-47b8-b6fc-3190ff065520",
            "hkey": 257020,
            "name": "Relais Villa Roncuzzi",
            "created_date": "2020-07-09T17:45:42.000Z",
            "updated_date": "2020-07-09T17:45:42.000Z",
            "checked": "1,2,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,19,27,28,29,30,31,32,33,34,35,37,38,39,40,41,42",
            "link": "https://www.villaroncuzzi.it/progetto-anticovid/",
            "program_name": "programma di soggiorno \"sicuricomeacasa\"",
            "version": 1,
            "terms": 2,
            "services": "breakfast,restaurant",
            "audit_date": "2020-06-17T00:00:00.000Z",
            "auditor": "PROGRAM",
            "chain_id": -1,
            "chain_name": "individual",
            "brand_id": -1,
            "brand_name": "n.a.",
            "city_id": 213680,
            "city": "Russi (Emilia Romagna)",
            "country_id": 65,
            "country": "Italy",
            "performance_cluster": 4,
            "status": false,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "003241af-d8f4-4488-9f61-1a57af2bfda2",
            "hkey": 878978,
            "name": "The Panari Residence",
            "created_date": "2020-07-10T11:44:54.000Z",
            "updated_date": "2020-07-10T11:44:54.000Z",
            "checked": null,
            "link": "https://www.hotel-audit.hrs.com/clean-and-safe",
            "program_name": "Clean & Safe Protocol",
            "version": 1,
            "terms": 2,
            "services": null,
            "audit_date": null,
            "auditor": null,
            "chain_id": 2118,
            "chain_name": "Travel Book UK",
            "brand_id": 2118,
            "brand_name": "Travel Book UK",
            "city_id": 45098,
            "city": "Nairobi (Nairobi)",
            "country_id": 78,
            "country": "Kenya",
            "performance_cluster": null,
            "status": false,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "0033e648-9505-4e3d-86b6-8ad23c8a8dcf",
            "hkey": 658889,
            "name": "City Junior Ciudad del Carmen Aeropuerto",
            "created_date": "2020-07-15T19:51:42.000Z",
            "updated_date": "2020-07-15T19:51:42.000Z",
            "checked": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46",
            "link": "https://safehotels.com/safehotels-covidclean-hotel-certification/",
            "program_name": "Safe Hotels Covid Clean",
            "version": 1,
            "terms": 2,
            "services": "breakfast,fitness",
            "audit_date": "2020-05-29T00:00:00.000Z",
            "auditor": "Safehotels Alliance",
            "chain_id": 993,
            "chain_name": "Hoteles City",
            "brand_id": 993,
            "brand_name": "Hoteles City",
            "city_id": 270378,
            "city": "Carmen (Nuevo Le\u00f3n)",
            "country_id": 102,
            "country": "Mexico",
            "performance_cluster": null,
            "status": true,
            "type": "cleansafe_expert_inspection"
        },
        {
            "id": "003e697b-4268-4b9b-a339-396733f64728",
            "hkey": 37925,
            "name": "Avon Gorge by Hotel du Vin",
            "created_date": "2020-07-22T09:55:16.000Z",
            "updated_date": "2020-07-22T09:55:16.000Z",
            "checked": "1,2,3,4,5,6,8,10,11,12,14,15,16,17,18,19,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46",
            "link": "https://www.hotel-audit.hrs.com/clean-and-safe",
            "program_name": "Clean & Safe Protocol",
            "version": 1,
            "terms": 2,
            "services": "breakfast,restaurant,mice",
            "audit_date": null,
            "auditor": null,
            "chain_id": 942,
            "chain_name": "Malmaison",
            "brand_id": 942,
            "brand_name": "Malmaison",
            "city_id": 63185,
            "city": "Bristol, City of Bristol (England)",
            "country_id": 50,
            "country": "United Kingdom",
            "performance_cluster": null,
            "status": true,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "00559a56-0d45-495b-bf1c-a267f900138b",
            "hkey": 3508,
            "name": "superior Hotel Cascade",
            "created_date": "2020-07-03T06:31:22.000Z",
            "updated_date": "2020-07-03T06:31:22.000Z",
            "checked": "1,2,3,4,5,6,7,8,10,11,12,9,14,15,16,17,18,19,27,28,29,30,35,36,37,39,40,41,42",
            "link": "https://www.hotel-audit.hrs.com/clean-and-safe",
            "program_name": "Clean & Safe Protocol",
            "version": 1,
            "terms": 2,
            "services": "breakfast",
            "audit_date": null,
            "auditor": null,
            "chain_id": -1,
            "chain_name": "individual",
            "brand_id": -1,
            "brand_name": "n.a.",
            "city_id": 97205,
            "city": "D\u00fcsseldorf (Nordrhein-Westfalen)",
            "country_id": 33,
            "country": "Germany",
            "performance_cluster": 2,
            "status": true,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "00683a6d-ba0b-482a-930b-a663f881a732",
            "hkey": 29433,
            "name": "Copthorne Hotel Slough Windsor",
            "created_date": "2020-07-13T15:28:53.000Z",
            "updated_date": "2020-07-13T15:28:53.000Z",
            "checked": "1,2,3,4,5,6,8,9,10,11,12,14,15,17,18,19,27,28,29,30,31,32,33,35,34,36,37,38,39,40,41,42,43,44,46,25,26,20",
            "link": "https://www.millenniumhotels.com/en/offers/global/wecleancarewelcome/",
            "program_name": "We Clean, We Care, We Welcome by Millennium Hotels and Resorts",
            "version": 1,
            "terms": 2,
            "services": "breakfast,restaurant,mice,fitness",
            "audit_date": null,
            "auditor": null,
            "chain_id": 81,
            "chain_name": "Millenium & Copthorne Hotels",
            "brand_id": 2353,
            "brand_name": "Millenium & Copthorne Hotels EMAE",
            "city_id": 32643,
            "city": "Slough (England)",
            "country_id": 50,
            "country": "United Kingdom",
            "performance_cluster": 3,
            "status": true,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "006a2c18-58c3-4ddc-92e5-f588e60f01bf",
            "hkey": 15878,
            "name": "VIENNA HOUSE TH\u00dcRINGER HOF EISENACH",
            "created_date": "2020-07-02T15:00:42.000Z",
            "updated_date": "2020-07-02T15:00:42.000Z",
            "checked": "1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46",
            "link": "https://www.hotel-audit.hrs.com/clean-and-safe",
            "program_name": "Clean & Safe Protocol",
            "version": 1,
            "terms": 2,
            "services": null,
            "audit_date": null,
            "auditor": null,
            "chain_id": 219,
            "chain_name": "VIENNA HOUSE",
            "brand_id": 219,
            "brand_name": "VIENNA HOUSE",
            "city_id": 68895,
            "city": "Eisenach (Th\u00fcringen)",
            "country_id": 33,
            "country": "Germany",
            "performance_cluster": 2,
            "status": true,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "00757446-5931-4bdc-b68b-25456349a8ff",
            "hkey": 3744,
            "name": "Arthotel ANA Enzian",
            "created_date": "2020-07-05T09:17:22.000Z",
            "updated_date": "2020-07-05T09:17:22.000Z",
            "checked": "1,2,3,4,5,6,7,8,10,11,12,9,14,15,16,17,18,19,27,28,29,30,35,36,37,39,40,41,42",
            "link": "https://www.hotel-audit.hrs.com/clean-and-safe",
            "program_name": "Clean & Safe Protocol",
            "version": 1,
            "terms": 2,
            "services": "breakfast",
            "audit_date": null,
            "auditor": null,
            "chain_id": 2928,
            "chain_name": "Gorgeous Smiling Chain Agreement",
            "brand_id": 2928,
            "brand_name": "Gorgeous Smiling Chain Agreement",
            "city_id": 45883,
            "city": "Wien (Wien)",
            "country_id": 114,
            "country": "Austria",
            "performance_cluster": 2,
            "status": true,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "0085cd7e-2857-490f-b481-1992fa7e82cb",
            "hkey": 537437,
            "name": "SSAW Boutique Hotel Nanchang",
            "created_date": "2020-07-21T07:02:09.000Z",
            "updated_date": "2020-07-21T07:02:09.000Z",
            "checked": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46",
            "link": "https://www.hotel-audit.hrs.com/group-assessment/2917/tiV2bl?utm_campaign=chain_central_approach&utm_content=2917&utm_medium=meeting&utm_source=hrs-hs",
            "program_name": "Self Inspected",
            "version": 1,
            "terms": 2,
            "services": "restaurant,breakfast",
            "audit_date": "2020-07-21T00:00:00.000Z",
            "auditor": "Zhang Rui",
            "chain_id": 2917,
            "chain_name": "SSAW Group",
            "brand_id": 2917,
            "brand_name": "SSAW Group",
            "city_id": 137255,
            "city": "Nanchang (Jiangxi Province)",
            "country_id": 29,
            "country": "China, P.R.",
            "performance_cluster": null,
            "status": true,
            "type": "cleansafe_expert_inspection"
        },
        {
            "id": "0093ffeb-57b4-40c9-9a32-9f4e4faea64d",
            "hkey": 728,
            "name": "DAN PANORAMA HAIFA",
            "created_date": "2020-07-16T08:59:47.000Z",
            "updated_date": "2020-07-16T08:59:47.000Z",
            "checked": "",
            "link": "https://www.danhotels.com/AboutDanhotels/News/Health_Statement",
            "program_name": "Dan hotels \"Stay safe & enjoy\" statement ",
            "version": 1,
            "terms": 2,
            "services": "",
            "audit_date": "2020-07-01T00:00:00.000Z",
            "auditor": "Dan hotels is working under the regulations of ministry of health of ISRAEL ",
            "chain_id": 8,
            "chain_name": "Dan Hotel Group-> Israel Leading Hotels",
            "brand_id": 8,
            "brand_name": "Dan Hotel Group-> Israel Leading Hotels",
            "city_id": 94242,
            "city": "Haifa (H\u0331efa)",
            "country_id": 64,
            "country": "Israel",
            "performance_cluster": 2,
            "status": false,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "00b0d4d1-473d-4b73-9644-a30462eb25b8",
            "hkey": 1866,
            "name": "Essener Hof Sure Hotel Collection by Best Western",
            "created_date": "2020-07-01T08:40:44.000Z",
            "updated_date": "2020-07-01T08:40:44.000Z",
            "checked": "1,2,3,4,5,6,8,10,11,12,14,15,16,17,18,19,27,28,29,30,31,35,36,37,39,40,41,42,43,44,45,46",
            "link": "https://www.essener-hof.com/en/hygienestandards-im-hotel-essener-hof",
            "program_name": "Our commitment for hygiene and safety",
            "version": 1,
            "terms": 2,
            "services": "breakfast,mice",
            "audit_date": null,
            "auditor": null,
            "chain_id": 60,
            "chain_name": "Best Western",
            "brand_id": 60,
            "brand_name": "Best Western",
            "city_id": 41146,
            "city": "Essen (Nordrhein-Westfalen)",
            "country_id": 33,
            "country": "Germany",
            "performance_cluster": 1,
            "status": true,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "00b2a3e4-785e-416e-9ea3-53f7178c2915",
            "hkey": 168744,
            "name": "Gut Schwaige",
            "created_date": "2020-06-29T16:36:47.000Z",
            "updated_date": "2020-06-29T16:36:47.000Z",
            "checked": "1,2,3,4,5,6,8,10,11,12,14,15,16,17,18,19,27,28,29,30,35,36,37,39,40,41,42",
            "link": "https://www.hotel-audit.hrs.com/clean-and-safe",
            "program_name": "Clean & Safe Protocol",
            "version": 1,
            "terms": 2,
            "services": "breakfast",
            "audit_date": null,
            "auditor": null,
            "chain_id": -1,
            "chain_name": "individual",
            "brand_id": -1,
            "brand_name": "n.a.",
            "city_id": 7106,
            "city": "Sch\u00e4ftlarn - Ebenhausen (Bayern)",
            "country_id": 33,
            "country": "Germany",
            "performance_cluster": 2,
            "status": true,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "00bdcd2e-80c9-418e-94ae-4b2a0fc80e80",
            "hkey": 4397,
            "name": "Dorint Hotel Alzey / Worms",
            "created_date": "2020-06-17T21:16:35.000Z",
            "updated_date": "2020-06-17T21:16:35.000Z",
            "checked": "1,2,3,4,5,6,8,10,11,12,14,15,16,18,19,27,28,29,30,31,32,33,34,35,36,37,39,40,41,42,43,44,46",
            "link": "https://www.hotel-audit.hrs.com/clean-and-safe",
            "program_name": "Clean & Safe Protocol",
            "version": 1,
            "terms": 1,
            "services": null,
            "audit_date": null,
            "auditor": null,
            "chain_id": 1192,
            "chain_name": "Dorint Hotels / Neue Dorint GmbH",
            "brand_id": 2881,
            "brand_name": "Dorint TAF",
            "city_id": 116962,
            "city": "Alzey (Rheinland-Pfalz)",
            "country_id": 33,
            "country": "Germany",
            "performance_cluster": 2,
            "status": true,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "00c59170-c62f-4d1d-81ba-4913b95b64a7",
            "hkey": 402300,
            "name": "Sejours et Affaires Grande Arche",
            "created_date": "2020-07-15T11:31:05.000Z",
            "updated_date": "2020-07-15T11:31:05.000Z",
            "checked": "1,2,3,4,5,6,8,9,10,11,12,14,15,16,17,18,19,20,21,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46",
            "link": "https://www.hotel-audit.hrs.com/clean-and-safe",
            "program_name": "Clean & Safe Protocol",
            "version": 1,
            "terms": 2,
            "services": "mice,fitness,breakfast",
            "audit_date": null,
            "auditor": null,
            "chain_id": 358,
            "chain_name": "Reside Etudes",
            "brand_id": 2162,
            "brand_name": "S\u00e9jours & Affaires",
            "city_id": 100178,
            "city": "Courbevoie (Ile-de-France)",
            "country_id": 43,
            "country": "France",
            "performance_cluster": 3,
            "status": true,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "00d0b46b-d000-42a6-ad3d-52fc1d9d342b",
            "hkey": 1027157,
            "name": "Bachar House By Fattal",
            "created_date": "2020-06-20T08:08:38.000Z",
            "updated_date": "2020-06-20T08:08:38.000Z",
            "checked": null,
            "link": "https://www.hotel-audit.hrs.com/clean-and-safe",
            "program_name": "Clean & Safe Protocol",
            "version": 1,
            "terms": 2,
            "services": null,
            "audit_date": null,
            "auditor": null,
            "chain_id": 1434,
            "chain_name": "Leonardo Hotels",
            "brand_id": 1434,
            "brand_name": "Leonardo Hotels",
            "city_id": -1,
            "city": "N.A.",
            "country_id": -1,
            "country": "N.A.",
            "performance_cluster": null,
            "status": false,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "00e47875-d96d-42c5-9650-f2e7bc8d0032",
            "hkey": 637777,
            "name": "Residhome Roissy Park",
            "created_date": "2020-07-15T11:31:05.000Z",
            "updated_date": "2020-07-15T11:31:05.000Z",
            "checked": "1,2,3,4,5,6,8,9,10,11,12,14,15,16,17,18,19,20,21,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46",
            "link": "https://www.hotel-audit.hrs.com/clean-and-safe",
            "program_name": "Clean & Safe Protocol",
            "version": 1,
            "terms": 2,
            "services": "mice,fitness,breakfast",
            "audit_date": null,
            "auditor": null,
            "chain_id": 358,
            "chain_name": "Reside Etudes",
            "brand_id": 2163,
            "brand_name": "Residhome",
            "city_id": 177173,
            "city": "Roissy-en-France (Ile-de-France)",
            "country_id": 43,
            "country": "France",
            "performance_cluster": 3,
            "status": true,
            "type": "cleansafe_self_inspection"
        },
        {
            "id": "0100981f-2aba-49ec-bf60-2b67d4b25219",
            "hkey": 937905,
            "name": "Serengeti Ikoma Wild Camp",
            "created_date": "2020-07-10T11:44:54.000Z",
            "updated_date": "2020-07-10T11:44:54.000Z",
            "checked": null,

In [12]:

df = pd.read_json (data)
df

,results,page_number,page_size,total_pages
0,"{'id': '0012e88e-c7d3-43f7-a406-efd7ee8a9612',...",1,100,56
1,"{'id': '0026579c-66c4-4845-b280-d7435ec627b8',...",1,100,56
2,"{'id': '002fed63-5e6e-47b8-b6fc-3190ff065520',...",1,100,56
3,"{'id': '003241af-d8f4-4488-9f61-1a57af2bfda2',...",1,100,56
4,"{'id': '0033e648-9505-4e3d-86b6-8ad23c8a8dcf',...",1,100,56
...,...,...,...,...
95,"{'id': '0486b860-17df-4fcd-b9df-590043ed6b2b',...",1,100,56
96,"{'id': '0490e55a-ef8a-4d60-8a2b-600df7f5c6ba',...",1,100,56
97,"{'id': '04952f3d-6641-44d6-9562-4a9620182527',...",1,100,56
98,"{'id': '049a738b-c481-4467-acb7-d36338afe538',...",1,100,56
99,"{'id': '04a3e1a5-48bd-4999-bc3b-1ee920286dea',...",1,100,56

In [14]:
type(parsed.get('results'))
df = pd.DataFrame(parsed.get('results'))
df

,id,hkey,name,created_date,updated_date,checked,link,program_name,version,terms,...,chain_name,brand_id,brand_name,city_id,city,country_id,country,performance_cluster,status,type
0,0012e88e-c7d3-43f7-a406-efd7ee8a9612,153403.0,Louisa's Place,2020-06-18T10:08:36.000Z,2020-06-18T10:08:36.000Z,"3,6,8,10,12,14,15,16,17,18,19,24,25,26,27,29,3...",https://travail-emploi.gouv.fr/IMG/pdf/protoco...,Protocole de déconfinement commun à toute la p...,1,1,...,individual,-1.0,n.a.,55133.0,Berlin (Berlin),33.0,Germany,2.0,False,cleansafe_self_inspection
1,0026579c-66c4-4845-b280-d7435ec627b8,260487.0,Castle Arch,2020-07-17T12:47:52.000Z,2020-07-17T12:47:52.000Z,"1,2,3,4,5,6,8,10,11,12,9,14,15,16,17,18,19,27,...",https://www.castlearchhotel.com/stay-safe-at-t...,Failte Ireland Covid 19 Safety charter,1,2,...,Magnuson Group,1988.0,Magnuson Group,3070924.0,Meath (Meath),62.0,Ireland,5.0,True,cleansafe_self_inspection
2,002fed63-5e6e-47b8-b6fc-3190ff065520,257020.0,Relais Villa Roncuzzi,2020-07-09T17:45:42.000Z,2020-07-09T17:45:42.000Z,"1,2,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,19,...",https://www.villaroncuzzi.it/progetto-anticovid/,"programma di soggiorno ""sicuricomeacasa""",1,2,...,individual,-1.0,n.a.,213680.0,Russi (Emilia Romagna),65.0,Italy,4.0,False,cleansafe_self_inspection
3,003241af-d8f4-4488-9f61-1a57af2bfda2,878978.0,The Panari Residence,2020-07-10T11:44:54.000Z,2020-07-10T11:44:54.000Z,None,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,Travel Book UK,2118.0,Travel Book UK,45098.0,Nairobi (Nairobi),78.0,Kenya,NaN,False,cleansafe_self_inspection
4,0033e648-9505-4e3d-86b6-8ad23c8a8dcf,658889.0,City Junior Ciudad del Carmen Aeropuerto,2020-07-15T19:51:42.000Z,2020-07-15T19:51:42.000Z,"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1...",https://safehotels.com/safehotels-covidclean-h...,Safe Hotels Covid Clean,1,2,...,Hoteles City,993.0,Hoteles City,270378.0,Carmen (Nuevo León),102.0,Mexico,NaN,True,cleansafe_expert_inspection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0486b860-17df-4fcd-b9df-590043ed6b2b,685323.0,Slim Balneario Camboriu by Slaviero Hoteis,2020-07-14T14:50:39.000Z,2020-07-14T14:50:39.000Z,"1,2,3,4,6,8,10,12,14,15,18,19,25,26,29,30,31,3...",https://www.slavierohoteis.com.br/wp-content/u...,Limpeza Garantida Slaviero Hotéis,1,2,...,Slaviero Hoteis,2146.0,Slaviero Hoteis,598337.0,Balneário Camboriú (Santa Catarina),23.0,Brazil,5.0,False,cleansafe_self_inspection
96,0490e55a-ef8a-4d60-8a2b-600df7f5c6ba,85694.0,Diament Hotel Plaza Katowice,2020-07-20T09:12:31.000Z,2020-07-20T09:12:31.000Z,None,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,DIAMENT,899.0,DIAMENT,107003.0,Katowice (Śląskie),122.0,Poland,4.0,False,cleansafe_self_inspection
97,04952f3d-6641-44d6-9562-4a9620182527,106989.0,Axis Ofir Beach Resort,2020-07-09T15:10:55.000Z,2020-07-09T15:10:55.000Z,"1,2,3,4,6,7,8,10,12,14,15,16,17,18,19,27,28,29...",https://www.axishoteis.com/Files/CleanSafe-EN.pdf,Clean & Safe,1,2,...,individual,-1.0,n.a.,214932.0,Esposende (Braga),123.0,Portugal,5.0,False,cleansafe_self_inspection
98,049a738b-c481-4467-acb7-d36338afe538,60830.0,Hesperia Vigo,2020-07-16T09:37:09.000Z,2020-07-16T09:37:09.000Z,"1,2,3,4,6,8,9,10,12,14,15,16,17,19,27,29,30,31...",https://diversey.com,Diversey,1,2,...,Hesperia Resorts,165.0,Hesperia Resorts,64919.0,Vigo (Galicia),140.0,Spain,3.0,False,cleansafe_self_inspection
99,04a3e1a5-48bd-4999-bc3b-1ee920286dea,123995.0,Rosewood Inn of the Anasazi,2020-07-21T07:33:24.000Z,2020-07-21T07:33:24.000Z,None,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,Rosewood Hotels & Resorts,79.0,Rosewood Hotels & Resorts,139974.0,Santa Fe (New Mexico),165.0,USA,NaN,False,cleansafe_self_inspection

In [98]:
results = []
results_df = pd.DataFrame()
url = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=1&size=100"
parsed = json.loads(requests.get(url).text)
#int(parsed['total_pages'])
for x in range(5):
    url_iter = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page="+str(x+1)+"&size=1"

    if res.status_code == 200:
        response = requests.get(url_iter)
        data = response.text
        parsed = json.loads(data)
        #df = pd.DataFrame(parsed.get('results'))
        results.append(parsed.get('results'))
    else: 
        print("Request failed page: {} ".format(x))

In [61]:
url = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=1&size=100"
parsed = json.loads(requests.get(url).text)
parsed

{'page_number': 1,
 'page_size': 100,
 'results': [{'audit_date': None,
   'auditor': None,
   'brand_id': -1,
   'brand_name': 'n.a.',
   'chain_id': -1,
   'chain_name': 'individual',
   'checked': '3,6,8,10,12,14,15,16,17,18,19,24,25,26,27,29,30,31,34,35,36,37,38,39,41,42',
   'city': 'Berlin (Berlin)',
   'city_id': 55133,
   'country': 'Germany',
   'country_id': 33,
   'created_date': '2020-06-18T10:08:36.000Z',
   'hkey': 153403,
   'id': '0012e88e-c7d3-43f7-a406-efd7ee8a9612',
   'link': 'https://travail-emploi.gouv.fr/IMG/pdf/protocole-deconfinement-covid-19-hcr.pdf',
   'name': "Louisa's Place",
   'performance_cluster': 2,
   'program_name': 'Protocole de déconfinement commun à toute la profession HCR',
   'services': 'breakfast,restaurant,fitness',
   'status': False,
   'terms': 1,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-06-18T10:08:36.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 1988,
   'brand_name': 'Magnuson Group',
   'chain_id': 1988,
   'chain_name': 'Magnuson Group',
   'checked': '1,2,3,4,5,6,8,10,11,12,9,14,15,16,17,18,19,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46',
   'city': 'Meath (Meath)',
   'city_id': 3070924,
   'country': 'Ireland',
   'country_id': 62,
   'created_date': '2020-07-17T12:47:52.000Z',
   'hkey': 260487,
   'id': '0026579c-66c4-4845-b280-d7435ec627b8',
   'link': 'https://www.castlearchhotel.com/stay-safe-at-the-castle-arch-hotel.html',
   'name': 'Castle Arch',
   'performance_cluster': 5,
   'program_name': 'Failte Ireland Covid 19 Safety charter',
   'services': 'breakfast,restaurant,mice',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-17T12:47:52.000Z',
   'version': 1},
  {'audit_date': '2020-06-17T00:00:00.000Z',
   'auditor': 'PROGRAM',
   'brand_id': -1,
   'brand_name': 'n.a.',
   'chain_id': -1,
   'chain_name': 'individual',
   'checked': '1,2,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,19,27,28,29,30,31,32,33,34,35,37,38,39,40,41,42',
   'city': 'Russi (Emilia Romagna)',
   'city_id': 213680,
   'country': 'Italy',
   'country_id': 65,
   'created_date': '2020-07-09T17:45:42.000Z',
   'hkey': 257020,
   'id': '002fed63-5e6e-47b8-b6fc-3190ff065520',
   'link': 'https://www.villaroncuzzi.it/progetto-anticovid/',
   'name': 'Relais Villa Roncuzzi',
   'performance_cluster': 4,
   'program_name': 'programma di soggiorno "sicuricomeacasa"',
   'services': 'breakfast,restaurant',
   'status': False,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-09T17:45:42.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 2118,
   'brand_name': 'Travel Book UK',
   'chain_id': 2118,
   'chain_name': 'Travel Book UK',
   'checked': None,
   'city': 'Nairobi (Nairobi)',
   'city_id': 45098,
   'country': 'Kenya',
   'country_id': 78,
   'created_date': '2020-07-10T11:44:54.000Z',
   'hkey': 878978,
   'id': '003241af-d8f4-4488-9f61-1a57af2bfda2',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'The Panari Residence',
   'performance_cluster': None,
   'program_name': 'Clean & Safe Protocol',
   'services': None,
   'status': False,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-10T11:44:54.000Z',
   'version': 1},
  {'audit_date': '2020-05-29T00:00:00.000Z',
   'auditor': 'Safehotels Alliance',
   'brand_id': 993,
   'brand_name': 'Hoteles City',
   'chain_id': 993,
   'chain_name': 'Hoteles City',
   'checked': '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46',
   'city': 'Carmen (Nuevo León)',
   'city_id': 270378,
   'country': 'Mexico',
   'country_id': 102,
   'created_date': '2020-07-15T19:51:42.000Z',
   'hkey': 658889,
   'id': '0033e648-9505-4e3d-86b6-8ad23c8a8dcf',
   'link': 'https://safehotels.com/safehotels-covidclean-hotel-certification/',
   'name': 'City Junior Ciudad del Carmen Aeropuerto',
   'performance_cluster': None,
   'program_name': 'Safe Hotels Covid Clean',
   'services': 'breakfast,fitness',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_expert_inspection',
   'updated_date': '2020-07-15T19:51:42.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': -1,
   'brand_name': 'n.a.',
   'chain_id': -1,
   'chain_name': 'individual',
   'checked': '1,2,3,4,5,6,7,8,10,11,12,9,14,15,16,17,18,19,27,28,29,30,35,36,37,39,40,41,42',
   'city': 'Düsseldorf (Nordrhein-Westfalen)',
   'city_id': 97205,
   'country': 'Germany',
   'country_id': 33,
   'created_date': '2020-07-03T06:31:22.000Z',
   'hkey': 3508,
   'id': '00559a56-0d45-495b-bf1c-a267f900138b',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'superior Hotel Cascade',
   'performance_cluster': 2,
   'program_name': 'Clean & Safe Protocol',
   'services': 'breakfast',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-03T06:31:22.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 2353,
   'brand_name': 'Millenium & Copthorne Hotels EMAE',
   'chain_id': 81,
   'chain_name': 'Millenium & Copthorne Hotels',
   'checked': '1,2,3,4,5,6,8,9,10,11,12,14,15,17,18,19,27,28,29,30,31,32,33,35,34,36,37,38,39,40,41,42,43,44,46,25,26,20',
   'city': 'Slough (England)',
   'city_id': 32643,
   'country': 'United Kingdom',
   'country_id': 50,
   'created_date': '2020-07-13T15:28:53.000Z',
   'hkey': 29433,
   'id': '00683a6d-ba0b-482a-930b-a663f881a732',
   'link': 'https://www.millenniumhotels.com/en/offers/global/wecleancarewelcome/',
   'name': 'Copthorne Hotel Slough Windsor',
   'performance_cluster': 3,
   'program_name': 'We Clean, We Care, We Welcome by Millennium Hotels and Resorts',
   'services': 'breakfast,restaurant,mice,fitness',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-13T15:28:53.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 219,
   'brand_name': 'VIENNA HOUSE',
   'chain_id': 219,
   'chain_name': 'VIENNA HOUSE',
   'checked': '1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46',
   'city': 'Eisenach (Thüringen)',
   'city_id': 68895,
   'country': 'Germany',
   'country_id': 33,
   'created_date': '2020-07-02T15:00:42.000Z',
   'hkey': 15878,
   'id': '006a2c18-58c3-4ddc-92e5-f588e60f01bf',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'VIENNA HOUSE THÜRINGER HOF EISENACH',
   'performance_cluster': 2,
   'program_name': 'Clean & Safe Protocol',
   'services': None,
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-02T15:00:42.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 2928,
   'brand_name': 'Gorgeous Smiling Chain Agreement',
   'chain_id': 2928,
   'chain_name': 'Gorgeous Smiling Chain Agreement',
   'checked': '1,2,3,4,5,6,7,8,10,11,12,9,14,15,16,17,18,19,27,28,29,30,35,36,37,39,40,41,42',
   'city': 'Wien (Wien)',
   'city_id': 45883,
   'country': 'Austria',
   'country_id': 114,
   'created_date': '2020-07-05T09:17:22.000Z',
   'hkey': 3744,
   'id': '00757446-5931-4bdc-b68b-25456349a8ff',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'Arthotel ANA Enzian',
   'performance_cluster': 2,
   'program_name': 'Clean & Safe Protocol',
   'services': 'breakfast',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-05T09:17:22.000Z',
   'version': 1},
  {'audit_date': '2020-07-21T00:00:00.000Z',
   'auditor': 'Zhang Rui',
   'brand_id': 2917,
   'brand_name': 'SSAW Group',
   'chain_id': 2917,
   'chain_name': 'SSAW Group',
   'checked': '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46',
   'city': 'Nanchang (Jiangxi Province)',
   'city_id': 137255,
   'country': 'China, P.R.',
   'country_id': 29,
   'created_date': '2020-07-21T07:02:09.000Z',
   'hkey': 537437,
   'id': '0085cd7e-2857-490f-b481-1992fa7e82cb',
   'link': 'https://www.hotel-audit.hrs.com/group-assessment/2917/tiV2bl?utm_campaign=chain_central_approach&utm_content=2917&utm_medium=meeting&utm_source=hrs-hs',
   'name': 'SSAW Boutique Hotel Nanchang',
   'performance_cluster': None,
   'program_name': 'Self Inspected',
   'services': 'restaurant,breakfast',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_expert_inspection',
   'updated_date': '2020-07-21T07:02:09.000Z',
   'version': 1},
  {'audit_date': '2020-07-01T00:00:00.000Z',
   'auditor': 'Dan hotels is working under the regulations of ministry of health of ISRAEL ',
   'brand_id': 8,
   'brand_name': 'Dan Hotel Group-> Israel Leading Hotels',
   'chain_id': 8,
   'chain_name': 'Dan Hotel Group-> Israel Leading Hotels',
   'checked': '',
   'city': 'Haifa (H̱efa)',
   'city_id': 94242,
   'country': 'Israel',
   'country_id': 64,
   'created_date': '2020-07-16T08:59:47.000Z',
   'hkey': 728,
   'id': '0093ffeb-57b4-40c9-9a32-9f4e4faea64d',
   'link': 'https://www.danhotels.com/AboutDanhotels/News/Health_Statement',
   'name': 'DAN PANORAMA HAIFA',
   'performance_cluster': 2,
   'program_name': 'Dan hotels "Stay safe & enjoy" statement ',
   'services': '',
   'status': False,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-16T08:59:47.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 60,
   'brand_name': 'Best Western',
   'chain_id': 60,
   'chain_name': 'Best Western',
   'checked': '1,2,3,4,5,6,8,10,11,12,14,15,16,17,18,19,27,28,29,30,31,35,36,37,39,40,41,42,43,44,45,46',
   'city': 'Essen (Nordrhein-Westfalen)',
   'city_id': 41146,
   'country': 'Germany',
   'country_id': 33,
   'created_date': '2020-07-01T08:40:44.000Z',
   'hkey': 1866,
   'id': '00b0d4d1-473d-4b73-9644-a30462eb25b8',
   'link': 'https://www.essener-hof.com/en/hygienestandards-im-hotel-essener-hof',
   'name': 'Essener Hof Sure Hotel Collection by Best Western',
   'performance_cluster': 1,
   'program_name': 'Our commitment for hygiene and safety',
   'services': 'breakfast,mice',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-01T08:40:44.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': -1,
   'brand_name': 'n.a.',
   'chain_id': -1,
   'chain_name': 'individual',
   'checked': '1,2,3,4,5,6,8,10,11,12,14,15,16,17,18,19,27,28,29,30,35,36,37,39,40,41,42',
   'city': 'Schäftlarn - Ebenhausen (Bayern)',
   'city_id': 7106,
   'country': 'Germany',
   'country_id': 33,
   'created_date': '2020-06-29T16:36:47.000Z',
   'hkey': 168744,
   'id': '00b2a3e4-785e-416e-9ea3-53f7178c2915',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'Gut Schwaige',
   'performance_cluster': 2,
   'program_name': 'Clean & Safe Protocol',
   'services': 'breakfast',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-06-29T16:36:47.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 2881,
   'brand_name': 'Dorint TAF',
   'chain_id': 1192,
   'chain_name': 'Dorint Hotels / Neue Dorint GmbH',
   'checked': '1,2,3,4,5,6,8,10,11,12,14,15,16,18,19,27,28,29,30,31,32,33,34,35,36,37,39,40,41,42,43,44,46',
   'city': 'Alzey (Rheinland-Pfalz)',
   'city_id': 116962,
   'country': 'Germany',
   'country_id': 33,
   'created_date': '2020-06-17T21:16:35.000Z',
   'hkey': 4397,
   'id': '00bdcd2e-80c9-418e-94ae-4b2a0fc80e80',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'Dorint Hotel Alzey / Worms',
   'performance_cluster': 2,
   'program_name': 'Clean & Safe Protocol',
   'services': None,
   'status': True,
   'terms': 1,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-06-17T21:16:35.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 2162,
   'brand_name': 'Séjours & Affaires',
   'chain_id': 358,
   'chain_name': 'Reside Etudes',
   'checked': '1,2,3,4,5,6,8,9,10,11,12,14,15,16,17,18,19,20,21,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46',
   'city': 'Courbevoie (Ile-de-France)',
   'city_id': 100178,
   'country': 'France',
   'country_id': 43,
   'created_date': '2020-07-15T11:31:05.000Z',
   'hkey': 402300,
   'id': '00c59170-c62f-4d1d-81ba-4913b95b64a7',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'Sejours et Affaires Grande Arche',
   'performance_cluster': 3,
   'program_name': 'Clean & Safe Protocol',
   'services': 'mice,fitness,breakfast',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-15T11:31:05.000Z',
   'version': 1},
  {'audit_date': '2020-06-16T00:00:00.000Z',
   'auditor': 'Francisco Serrano ( Project Manager )',
   'brand_id': 548,
   'brand_name': 'abba Hoteles Group',
   'chain_id': 548,
   'chain_name': 'abba Hoteles Group',
   'checked': '1,2,3,4,5,6,7,8,9,10,12,14,15,16,17,18,19,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,46',
   'city': 'Esplugues de Llobregat (Cataluña)',
   'city_id': 131841,
   'country': 'Spain',
   'country_id': 140,
   'created_date': '2020-07-16T10:25:48.000Z',
   'hkey': 145133,
   'id': '00cc117c-804d-4839-a4de-15b7988e6b48',
   'link': 'https://www.bureauveritas.es/newsroom/certificacion-global-clean-site-reapertura-hosteleria-restauracion-comercio-covid-23',
   'name': 'abba Garden',
   'performance_cluster': 2,
   'program_name': 'Global Safe Site',
   'services': 'breakfast,mice,spa',
   'status': False,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-16T10:25:48.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 1434,
   'brand_name': 'Leonardo Hotels',
   'chain_id': 1434,
   'chain_name': 'Leonardo Hotels',
   'checked': None,
   'city': 'N.A.',
   'city_id': -1,
   'country': 'N.A.',
   'country_id': -1,
   'created_date': '2020-06-20T08:08:38.000Z',
   'hkey': 1027157,
   'id': '00d0b46b-d000-42a6-ad3d-52fc1d9d342b',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'Bachar House By Fattal',
   'performance_cluster': None,
   'program_name': 'Clean & Safe Protocol',
   'services': None,
   'status': False,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-06-20T08:08:38.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 2163,
   'brand_name': 'Residhome',
   'chain_id': 358,
   'chain_name': 'Reside Etudes',
   'checked': '1,2,3,4,5,6,8,9,10,11,12,14,15,16,17,18,19,20,21,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46',
   'city': 'Roissy-en-France (Ile-de-France)',
   'city_id': 177173,
   'country': 'France',
   'country_id': 43,
   'created_date': '2020-07-15T11:31:05.000Z',
   'hkey': 637777,
   'id': '00e47875-d96d-42c5-9650-f2e7bc8d0032',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'Residhome Roissy Park',
   'performance_cluster': 3,
   'program_name': 'Clean & Safe Protocol',
   'services': 'mice,fitness,breakfast',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-15T11:31:05.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 2118,
   'brand_name': 'Travel Book UK',
   'chain_id': 2118,
   'chain_name': 'Travel Book UK',
   'checked': None,
   'city': 'Karatu',
   'city_id': 1248787,
   'country': 'Tanzania',
   'country_id': 150,
   'created_date': '2020-07-10T11:44:54.000Z',
   'hkey': 937905,
   'id': '0100981f-2aba-49ec-bf60-2b67d4b25219',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'Serengeti Ikoma Wild Camp',
   'performance_cluster': None,
   'program_name': 'Clean & Safe Protocol',
   'services': None,
   'status': False,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-10T11:44:54.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 1091,
   'brand_name': 'Synxis',
   'chain_id': 1091,
   'chain_name': 'Synxis',
   'checked': '1,2,3,4,5,6,8,10,11,12,14,15,17,18,19,27,28,29,30,31,35,36,37,39,40,41,42',
   'city': 'Perth (State of Western Australia)',
   'city_id': 19645,
   'country': 'Australia',
   'country_id': 10,
   'created_date': '2020-07-09T01:05:03.000Z',
   'hkey': 40625,
   'id': '010bd4dd-f6fd-4d06-b445-77c5bcaf76b0',
   'link': 'https://metrohotels.com.au/wp-content/uploads/2020/03/METRO-HOTEL-PERTH-COVID-19-POLICY.pdf',
   'name': 'Metro Hotel Perth',
   'performance_cluster': 5,
   'program_name': 'COVID-19 Policy Statement',
   'services': 'breakfast',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-09T01:05:03.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 2146,
   'brand_name': 'Slaviero Hoteis',
   'chain_id': 2146,
   'chain_name': 'Slaviero Hoteis',
   'checked': '1,2,3,4,6,8,10,12,14,15,18,19,25,26,29,30,31,33,35,36,38,41,43,44,46',
   'city': 'São Paulo (São Paulo)',
   'city_id': 46097,
   'country': 'Brazil',
   'country_id': 23,
   'created_date': '2020-07-14T14:50:39.000Z',
   'hkey': 883488,
   'id': '01189128-cb37-4ec9-a84e-ede4d9e5f641',
   'link': 'https://www.slavierohoteis.com.br/wp-content/uploads/limpeza-garantida-slaviero-manual-boas-praticas.pdf',
   'name': 'Slaviero Essential Sao Paulo Moema',
   'performance_cluster': 2,
   'program_name': 'Limpeza Garantida Slaviero Hotéis',
   'services': 'spa,fitness,restaurant,breakfast,mice',
   'status': False,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-14T14:50:39.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 1089,
   'brand_name': 'Ihotelier/TravelClick',
   'chain_id': 1089,
   'chain_name': 'Ihotelier/TravelClick',
   'checked': '1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,29,30,35,36,37,39,40,41,42',
   'city': 'Brisbane (State of Queensland)',
   'city_id': 229011,
   'country': 'Australia',
   'country_id': 10,
   'created_date': '2020-07-06T04:36:09.000Z',
   'hkey': 406241,
   'id': '013ffbe7-b9a3-4f0e-b355-52304513aace',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'MANOR APARTMENT HOTEL',
   'performance_cluster': 4,
   'program_name': 'Clean & Safe Protocol',
   'services': 'breakfast',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-06T04:42:23.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': 1094,
   'brand_name': 'Radisson Hotel Group (Opt-in 14%)',
   'chain_id': 67,
   'chain_name': 'Radisson Hotel Group',
   'checked': '1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,32,33,34,35,36,37,39,40,41,42,44,46',
   'city': 'Boulogne-Billancourt (Ile-de-France)',
   'city_id': 98782,
   'country': 'France',
   'country_id': 43,
   'created_date': '2020-07-17T08:41:38.000Z',
   'hkey': 383464,
   'id': '01523870-e827-4a5d-a87b-0ee905d94688',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'RADISSON BLU PARIS-BOULOGNE',
   'performance_cluster': 2,
   'program_name': 'Clean & Safe Protocol',
   'services': 'breakfast,restaurant,mice',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-17T08:41:38.000Z',
   'version': 1},
  {'audit_date': None,
   'auditor': None,
   'brand_id': -1,
   'brand_name': 'n.a.',
   'chain_id': -1,
   'chain_name': 'individual',
   'checked': '1,2,3,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,19,27,28,29,30,31,35,36,37,39,40,41,42',
   'city': 'Wolfsburg (Niedersachsen)',

In [100]:
results
#df = pd.DataFrame(results)

[[{'audit_date': None,
   'auditor': None,
   'brand_id': -1,
   'brand_name': 'n.a.',
   'chain_id': -1,
   'chain_name': 'individual',
   'checked': '3,6,8,10,12,14,15,16,17,18,19,24,25,26,27,29,30,31,34,35,36,37,38,39,41,42',
   'city': 'Berlin (Berlin)',
   'city_id': 55133,
   'country': 'Germany',
   'country_id': 33,
   'created_date': '2020-06-18T10:08:36.000Z',
   'hkey': 153403,
   'id': '0012e88e-c7d3-43f7-a406-efd7ee8a9612',
   'link': 'https://travail-emploi.gouv.fr/IMG/pdf/protocole-deconfinement-covid-19-hcr.pdf',
   'name': "Louisa's Place",
   'performance_cluster': 2,
   'program_name': 'Protocole de déconfinement commun à toute la profession HCR',
   'services': 'breakfast,restaurant,fitness',
   'status': False,
   'terms': 1,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-06-18T10:08:36.000Z',
   'version': 1}],
 [{'audit_date': None,
   'auditor': None,
   'brand_id': 1988,
   'brand_name': 'Magnuson Group',
   'chain_id': 1988,
   'chain_name': 'Magnuson Group',
   'checked': '1,2,3,4,5,6,8,10,11,12,9,14,15,16,17,18,19,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46',
   'city': 'Meath (Meath)',
   'city_id': 3070924,
   'country': 'Ireland',
   'country_id': 62,
   'created_date': '2020-07-17T12:47:52.000Z',
   'hkey': 260487,
   'id': '0026579c-66c4-4845-b280-d7435ec627b8',
   'link': 'https://www.castlearchhotel.com/stay-safe-at-the-castle-arch-hotel.html',
   'name': 'Castle Arch',
   'performance_cluster': 5,
   'program_name': 'Failte Ireland Covid 19 Safety charter',
   'services': 'breakfast,restaurant,mice',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-17T12:47:52.000Z',
   'version': 1}],
 [{'audit_date': '2020-06-17T00:00:00.000Z',
   'auditor': 'PROGRAM',
   'brand_id': -1,
   'brand_name': 'n.a.',
   'chain_id': -1,
   'chain_name': 'individual',
   'checked': '1,2,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,19,27,28,29,30,31,32,33,34,35,37,38,39,40,41,42',
   'city': 'Russi (Emilia Romagna)',
   'city_id': 213680,
   'country': 'Italy',
   'country_id': 65,
   'created_date': '2020-07-09T17:45:42.000Z',
   'hkey': 257020,
   'id': '002fed63-5e6e-47b8-b6fc-3190ff065520',
   'link': 'https://www.villaroncuzzi.it/progetto-anticovid/',
   'name': 'Relais Villa Roncuzzi',
   'performance_cluster': 4,
   'program_name': 'programma di soggiorno "sicuricomeacasa"',
   'services': 'breakfast,restaurant',
   'status': False,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-09T17:45:42.000Z',
   'version': 1}],
 [{'audit_date': None,
   'auditor': None,
   'brand_id': 2118,
   'brand_name': 'Travel Book UK',
   'chain_id': 2118,
   'chain_name': 'Travel Book UK',
   'checked': None,
   'city': 'Nairobi (Nairobi)',
   'city_id': 45098,
   'country': 'Kenya',
   'country_id': 78,
   'created_date': '2020-07-10T11:44:54.000Z',
   'hkey': 878978,
   'id': '003241af-d8f4-4488-9f61-1a57af2bfda2',
   'link': 'https://www.hotel-audit.hrs.com/clean-and-safe',
   'name': 'The Panari Residence',
   'performance_cluster': None,
   'program_name': 'Clean & Safe Protocol',
   'services': None,
   'status': False,
   'terms': 2,
   'type': 'cleansafe_self_inspection',
   'updated_date': '2020-07-10T11:44:54.000Z',
   'version': 1}],
 [{'audit_date': '2020-05-29T00:00:00.000Z',
   'auditor': 'Safehotels Alliance',
   'brand_id': 993,
   'brand_name': 'Hoteles City',
   'chain_id': 993,
   'chain_name': 'Hoteles City',
   'checked': '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46',
   'city': 'Carmen (Nuevo León)',
   'city_id': 270378,
   'country': 'Mexico',
   'country_id': 102,
   'created_date': '2020-07-15T19:51:42.000Z',
   'hkey': 658889,
   'id': '0033e648-9505-4e3d-86b6-8ad23c8a8dcf',
   'link': 'https://safehotels.com/safehotels-covidclean-hotel-certification/',
   'name': 'City Junior Ciudad del Carmen Aeropuerto',
   'performance_cluster': None,
   'program_name': 'Safe Hotels Covid Clean',
   'services': 'breakfast,fitness',
   'status': True,
   'terms': 2,
   'type': 'cleansafe_expert_inspection',
   'updated_date': '2020-07-15T19:51:42.000Z',
   'version': 1}]]

In [77]:
for x in range(0,3):
    url_iter = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page="+str(x+1)+"&size=1"
    print(url_iter)

https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=1&size=1
https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=2&size=1
https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=3&size=1

In [97]:
df

                                                    0
0   {'id': '0012e88e-c7d3-43f7-a406-efd7ee8a9612',...
1   {'id': '0026579c-66c4-4845-b280-d7435ec627b8',...
2   {'id': '002fed63-5e6e-47b8-b6fc-3190ff065520',...
3   {'id': '003241af-d8f4-4488-9f61-1a57af2bfda2',...
4   {'id': '0033e648-9505-4e3d-86b6-8ad23c8a8dcf',...
5   {'id': '00559a56-0d45-495b-bf1c-a267f900138b',...
6   {'id': '00683a6d-ba0b-482a-930b-a663f881a732',...
7   {'id': '006a2c18-58c3-4ddc-92e5-f588e60f01bf',...
8   {'id': '00757446-5931-4bdc-b68b-25456349a8ff',...
9   {'id': '0085cd7e-2857-490f-b481-1992fa7e82cb',...
10  {'id': '0093ffeb-57b4-40c9-9a32-9f4e4faea64d',...
11  {'id': '00b0d4d1-473d-4b73-9644-a30462eb25b8',...
12  {'id': '00b2a3e4-785e-416e-9ea3-53f7178c2915',...
13  {'id': '00bdcd2e-80c9-418e-94ae-4b2a0fc80e80',...
14  {'id': '00c59170-c62f-4d1d-81ba-4913b95b64a7',...
15  {'id': '00cc117c-804d-4839-a4de-15b7988e6b48',...
16  {'id': '00d0b46b-d000-42a6-ad3d-52fc1d9d342b',...
17  {'id': '00e47875-d96d-42c5-9650-f2e7bc8d0032',...
18  {'id': '0100981f-2aba-49ec-bf60-2b67d4b25219',...
19  {'id': '010bd4dd-f6fd-4d06-b445-77c5bcaf76b0',...
20  {'id': '01189128-cb37-4ec9-a84e-ede4d9e5f641',...
21  {'id': '013ffbe7-b9a3-4f0e-b355-52304513aace',...
22  {'id': '01523870-e827-4a5d-a87b-0ee905d94688',...
23  {'id': '0158a05f-230e-4d16-9e71-c57c38fe567a',...
24  {'id': '015b06bb-e180-4fed-af6f-1c6158c1c206',...
25  {'id': '015b7baa-3241-4737-b2e9-c98ca83be79d',...
26  {'id': '01656bae-4af4-4833-925a-155c2963f44c',...
27  {'id': '017cbe7e-0b17-458e-8f1f-79ac64a0eb87',...
28  {'id': '01823b45-2f05-4c9e-9006-7cf53e859126',...
29  {'id': '0193a01e-3fd4-4391-a6bc-6abed336a9d5',...
30  {'id': '01985cc0-2223-48d9-b9fe-178da7007ac2',...
31  {'id': '01a08d01-41dd-4331-8dd7-a24b35c73dd0',...
32  {'id': '01a32455-9480-45e1-93ca-d3fb90503028',...
33  {'id': '01ac671d-3c88-472f-b0b2-6d274c4fc53a',...
34  {'id': '01b85b8f-45b0-4b11-9b5b-dabc42d5b4b7',...
35  {'id': '01bb2075-3ed1-4a13-91cf-6195aaaddafc',...
36  {'id': '01c0a20e-3f6d-4840-b9b3-eb55b4181295',...
37  {'id': '01c2d58d-f0e5-4d78-a3e6-f91e2b28feaf',...
38  {'id': '01c9e4b4-6d70-4d19-af1e-b52c67affc08',...
39  {'id': '01db42b1-09c5-4b76-a8ca-23d908e24a21',...
40  {'id': '01edf922-046f-40ef-b0cd-a139fbf26373',...
41  {'id': '01f3976f-7caf-4b8a-b523-f7d41c60052f',...
42  {'id': '0219b1c4-cac3-4030-ab0b-61aa15ada92b',...
43  {'id': '021a2b80-a16c-4823-a4fd-6bf9efb46751',...
44  {'id': '021ef002-141a-49a6-8b73-a51fa38b9cbe',...
45  {'id': '022af1d3-457a-4f60-89aa-0e8bf02c0750',...
46  {'id': '025080b7-bf38-45b9-baa6-8a84a80a0bf5',...
47  {'id': '025226de-c3bb-4574-ab5f-b9c7b1abae30',...
48  {'id': '025b509b-83b1-4679-b5ec-5e9762dea288',...
49  {'id': '025e97b9-c412-4850-b389-c8caff9c2ac3',...
50  {'id': '02621b6b-41e5-4f17-a1c5-f0d31a865fbb',...
51  {'id': '026fa063-f7ec-4340-8175-47196fa2d601',...
52  {'id': '0272e6c3-1fc7-4a75-8625-3afe4a58889e',...

In [6]:
json_normalize(df, 0)

NameError: name 'json_normalize' is not defined

In [ ]:
import requests
import json
import pandas as pd
final_df = pd.DataFrame()
url = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=1&size=100"
response = requests.get(url)
data = response.text
parsed = json.loads(data)
df = pd.DataFrame(parsed.get('results'))
final_df = final_df.append(df)

In [25]:
final_df = pd.DataFrame()
url = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=1&size=100"
parsed = json.loads(requests.get(url).text)
#int(parsed['total_pages'])
for x in range(int(parsed['total_pages'])):
    url_iter = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page="+str(x+1)+"&size=100"
    response = requests.get(url_iter)
    
    if response.status_code == 200:    
        data = response.text
        parsed = json.loads(data)
        df = pd.DataFrame(parsed.get('results'))
        final_df = final_df.append(df, ignore_index=True)
    else: 
        print("Request failed page: {} ".format(x))
final_df.shape

(5575, 24)

In [26]:
final_df.head()

,id,hkey,name,created_date,updated_date,checked,link,program_name,version,terms,...,chain_name,brand_id,brand_name,city_id,city,country_id,country,performance_cluster,status,type
0,0012e88e-c7d3-43f7-a406-efd7ee8a9612,153403.0,Louisa's Place,2020-06-18T10:08:36.000Z,2020-06-18T10:08:36.000Z,"3,6,8,10,12,14,15,16,17,18,19,24,25,26,27,29,3...",https://travail-emploi.gouv.fr/IMG/pdf/protoco...,Protocole de déconfinement commun à toute la p...,1,1,...,individual,-1.0,n.a.,55133.0,Berlin (Berlin),33.0,Germany,2.0,False,cleansafe_self_inspection
1,0026579c-66c4-4845-b280-d7435ec627b8,260487.0,Castle Arch,2020-07-17T12:47:52.000Z,2020-07-17T12:47:52.000Z,"1,2,3,4,5,6,8,10,11,12,9,14,15,16,17,18,19,27,...",https://www.castlearchhotel.com/stay-safe-at-t...,Failte Ireland Covid 19 Safety charter,1,2,...,Magnuson Group,1988.0,Magnuson Group,3070924.0,Meath (Meath),62.0,Ireland,5.0,True,cleansafe_self_inspection
2,002fed63-5e6e-47b8-b6fc-3190ff065520,257020.0,Relais Villa Roncuzzi,2020-07-09T17:45:42.000Z,2020-07-09T17:45:42.000Z,"1,2,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,19,...",https://www.villaroncuzzi.it/progetto-anticovid/,"programma di soggiorno ""sicuricomeacasa""",1,2,...,individual,-1.0,n.a.,213680.0,Russi (Emilia Romagna),65.0,Italy,4.0,False,cleansafe_self_inspection
3,003241af-d8f4-4488-9f61-1a57af2bfda2,878978.0,The Panari Residence,2020-07-10T11:44:54.000Z,2020-07-10T11:44:54.000Z,None,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,Travel Book UK,2118.0,Travel Book UK,45098.0,Nairobi (Nairobi),78.0,Kenya,NaN,False,cleansafe_self_inspection
4,0033e648-9505-4e3d-86b6-8ad23c8a8dcf,658889.0,City Junior Ciudad del Carmen Aeropuerto,2020-07-15T19:51:42.000Z,2020-07-15T19:51:42.000Z,"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1...",https://safehotels.com/safehotels-covidclean-h...,Safe Hotels Covid Clean,1,2,...,Hoteles City,993.0,Hoteles City,270378.0,Carmen (Nuevo León),102.0,Mexico,NaN,True,cleansafe_expert_inspection

In [ ]:
C.writeData(R, table = 'mytable')
print(R)