In [7]:
import requests
import json
import pandas as pd

### Initialize the dataframe
final_df = pd.DataFrame()

### API link
url = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=1&size=100"
parsed = json.loads(requests.get(url).text)
### Get the number of pages through -> #int(parsed['total_pages'])
for x in range(int(parsed['total_pages'])):
    url_iter = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page="+str(x+1)+"&size=100"
    response = requests.get(url_iter)
    
    if response.status_code == 200:    
        data = response.text
        parsed = json.loads(data)
        df = pd.DataFrame(parsed.get('results'))
        final_df = final_df.append(df, ignore_index=True)
    else: 
        print("Request failed page: {} ".format(x))
final_df.shape

,id,hkey,name,created_date,updated_date,checked,link,program_name,version,terms,...,brand_id,brand_name,city_id,city,country_id,country,performance_cluster,status,type,missed
0,00005b15-b99c-444d-97bf-d3cd02f8c8db,431251,Homewood Suites by Hilton Atlanta I-85-Lawrenc...,2020-07-31T16:16:24.000Z,2020-07-31T16:16:24.000Z,"1,2,3,4,5,6,8,10,11,12,13,14,15,16,17,18,19,20...",https://www.hilton.com/en/corporate/cleanstay/,Hilton CleanStayTM,1,2,...,1537,Homewood Suites by Hilton,168172,Lawrenceville,165,USA,4.0,True,cleansafe_self_inspection,
1,00008c26-5cc5-4655-8170-7fdee1808e5d,110020,QUALITY INN BARRIE,2021-03-30T20:04:45.000Z,2021-03-30T20:04:45.000Z,"1,2,3,4,5,6,7,8,10,11,12,9,14,15,16,17,18,19,2...",https://www.choicehotels.com/en-au/about/commi...,Choice Hotels Commitment to Clean,1,2,...,1760,Quality by Choice,665022,Barrie,75,Canada,5.0,True,cleansafe_self_inspection,
2,000225aa-e50c-46c0-a3fe-65813215f837,442825,Hampton Inn - Suites Mount Pleasant,2020-07-31T16:16:24.000Z,2020-07-31T16:16:24.000Z,"1,2,3,4,5,6,8,10,11,12,13,14,15,16,17,18,19,20...",https://www.hilton.com/en/corporate/cleanstay/,Hilton CleanStayTM,1,2,...,1535,Hampton Inn by Hilton,190895,Mount Pleasant,165,USA,5.0,True,cleansafe_self_inspection,
3,0002b8e5-2d6c-4334-8aa4-5c831da5a5bf,373376,Sleep Inn Raleigh Durham Airport,2021-03-30T20:04:56.000Z,2021-03-30T20:04:56.000Z,"1,2,3,4,5,6,7,8,10,11,12,9,14,15,16,17,18,19,2...",https://www.choicehotels.com/en-au/about/commi...,Choice Hotels Commitment to Clean,1,2,...,1761,Sleep Inn by Choice,131636,DURHAM,165,USA,NaN,True,cleansafe_self_inspection,
4,00047545-725b-415b-ae11-642fefb43dca,61,Best Western Hotel Domicil,2021-01-06T15:33:26.000Z,2021-01-11T10:35:52.000Z,"1,2,3,4,5,6,7,8,10,11,12,9,14,15,16,17,18,19,2...",https://www.bestwestern.it/hotels/specialprote...,We Care Clean,1,2,...,60,Best Western,92734,Bonn,33,Germany,1.0,True,cleansafe_self_inspection,

In [3]:
from datetime import dt
final_df.to_excel('C:\\Users\\svi02\\Documents\CleanAndSafe\\'+str(dt.today())+'_CleanAndSafe_list.xlsx', 
              sheet_name='CleanAndSafeHotels', 
              header=True,
              encoding='utf-8',
              index=False,
              freeze_panes=(1,0) )

C:\Anaconda\lib\site-packages\xlsxwriter\worksheet.py:830: UserWarning: Ignoring URL 'https://uc03e8b39e71edf16e2eb8fca677.dl.dropboxusercontent.com/cd/0/inline2/A8Ef_V6nYWiL7Pfnfls0jzRUI1Mgh-Iw1ZaREDD1zL-Wg5x7fVQHWdaQGpwLJvWvh94kB2GzO0dg58SyQTdKndsU_UzDfbwwcu7Dyj2TM6YL9omVo3JHIVlB1CXVWZFWEJm3qwb8BjFDHxpyv8qMCQEgKck_PsUohr53VjJBSvVxIe2X4m5PDhrGKuENz2_LhzRicbtjOQspqZGb55YbbHF_7MbUoQlEeW4lFJXD2vra2uqNSzSiVreTfCBg-JU2N-SVJY6qb6P_GXs2UkVvidhEJRJWk86Hk27N4Ds2FDX31lDSuhSs4RKf4U7NJBg4cp2AtJG2ZUzvFryPY534e59AkQmb9IMRbpYlzbMIS9mdig/file' with link or location/anchor > 255 characters since it exceeds Excel's limit for URLS
  force_unicode(url))
C:\Anaconda\lib\site-packages\xlsxwriter\worksheet.py:830: UserWarning: Ignoring URL 'https://thailandsha.tourismthailand.org/shalists/index?type=2-%E0%B9%82%E0%B8%A3%E0%B8%87%E0%B9%81%E0%B8%A3%E0%B8%A1%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%9E%E0%B8%B1%E0%B8%81%20%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%88%E0%B8%B1%E0%B8%94%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%8A%E0%B8%B8%E0%B8%A1&province=11-%E0%B8%AA%E0%B8%A1%E0%B8%B8%E0%B8%97%E0%B8%A3%E0%B8%9B%E0%B8%A3%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A3' with link or location/anchor > 255 characters since it exceeds Excel's limit for URLS
  force_unicode(url))
C:\Anaconda\lib\site-packages\xlsxwriter\worksheet.py:830: UserWarning: Ignoring URL 'https://federalberghicervia.it/news-alberghi-cervia-milano-marittima/notizia/accoglienza-sicura-manuale-per-le-strutture-turistico-ricettive.html?file=file/usr/news/estate-2020/allegato-circ253-accoglienza-sicura-manuale-per-le-strutture-turistico-ricettive-150620.pdf' with link or location/anchor > 255 characters since it exceeds Excel's limit for URLS
  force_unicode(url))
C:\Anaconda\lib\site-packages\xlsxwriter\worksheet.py:830: UserWarning: Ignoring URL 'https://www.hotelleriesuisse.ch/fr/prestations-et-soutien/coronavirus/exploitation-dhotel/hygiene-et-protection?_cldee=cGF0cmljay56dWZmZXJleUB0dWxpcGlubmxhdXNhbm5lLmNo&recipientid=contact-fd5fa2fb4482e21199f7005056870001-7b3199451c1e492eb80437af2b7c5068&esid=4d0fee3f-87b4-ea11-9157-005056b6670b' with link or location/anchor > 255 characters since it exceeds Excel's limit for URLS
  force_unicode(url))
C:\Anaconda\lib\site-packages\xlsxwriter\worksheet.py:830: UserWarning: Ignoring URL 'https://uc7ec614524d92b2fd15b7c10ac9.dl.dropboxusercontent.com/cd/0/inline2/A8BpWPc3ENqqRalslLZKaXVmuqBOQApuRlFfA5CDJNc8tLoxIDl7W8ApfT49uQ1EP1oQKzwATd4uVmdV1tRUdz4SZkbRKBChG_HY44bJQicS4YSGzbP7Z1BxJq32d2HZ2LrxH0YcQJO8cFivd3VlTTue2KBxXwm96TaVRVtGsassGNSKFgACEup6kiWBBPjxh9kcfPmo5D_wIX7EPxH2ib5lVebcOHfj7hWvjo0RxQ5TlhvTPv2MvNRYpVYVDa6xUJtaW2KjU4y0LQj2sstCqvudzzipaChLhl7uWqmZK53GetR_NvMBmVcKtLRRg8PRO91IUXVTND4TN_5IMwOe7VcK5nXRZ9W6O_T-Lgfetap7Tw/file' with link or location/anchor > 255 characters since it exceeds Excel's limit for URLS
  force_unicode(url))
C:\Anaconda\lib\site-packages\xlsxwriter\worksheet.py:830: UserWarning: Ignoring URL 'https://uca4624dd1eb0b2ef3edf24faa7c.dl.dropboxusercontent.com/cd/0/inline2/A75lAqEbBTK5oKAkk65mxLAUHc-FTLrWpgvVOSucteVKvVeomRyoCxuTdDTtMzL9U-kKlQvaBMbHYVdhNcGQzE_6A6SaBaajHn8gBvNLJE89_PnMbpLwnhsAO6PwI6FvBTWtYZMuyWSZuEKP2rO1VPdhUTYxw2CEFPyRcCt2C1oyLnoeXKgKrzg5EQbYdU_5C5ytzM1QNijVnNcHQxVYDJcKgz2x2voqyZkOnTaq1OhI7UlbD0GxAU8lTBOU_sYYbmt7N3X3-QnIpyAXoY8-8wIBHqR2MsXEWwr4uQniJfPBlhQx2OcRzuLdeytAwCrn_YEjgKoZUgUhKbIKXNKzfpSoqgUsCoCN5RbozWVyWs2OvA/file' with link or location/anchor > 255 characters since it exceeds Excel's limit for URLS
  force_unicode(url))

In [2]:
final_df['created_date']= pd.to_datetime(final_df['created_date'])
final_df['updated_date']= pd.to_datetime(final_df['updated_date'])
harmonized_df = final_df[final_df.hkey.notnull()]
# harmonized_df = harmonized_df.loc[:, harmonized_df.columns != 'checked']

In [65]:
#harmonized_df[harmonized_df.hkey.isnull()]
print(f'Number of records having HOTEL_IDs {final_df.id[final_df.hkey.notnull()].count()}.')
print(f'Number of records with no HOTEL_IDs  {final_df.id[final_df.hkey.isna()].count()}.')

Number of records having HOTEL_IDs 6924.
Number of records with no HOTEL_IDs  27.

In [3]:
# harmonized_df = harmonized_df.head(10)
harmonized_df['checked_id'] = harmonized_df['checked']
harmonized_df.drop(['checked'], axis= 1, inplace = True)

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Anaconda\lib\site-packages\pandas\core\frame.py:4117: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [123]:
harmonized_df.shape

(15109, 25)

In [124]:
import pyexasol
import configparser

#Location of the ini file
config = configparser.ConfigParser()
config.read('C:\\Users\\svi02\\.spyder-py3\\pfxIUTO.ini')
dsn=config['pfxIUT']['dsn']
user=config['pfxIUT']['user']
pwd=config['pfxIUT']['pwd']
schema=config['pfxIUT']['schema']
# Exasol connection
connect = pyexasol.connect(dsn=dsn, user=user, password=pwd, schema=schema)
connect.execute("TRUNCATE TABLE DWHPFX.CLEAN_SAFE_HOTELS")
connect.import_from_pandas(harmonized_df, table = ('DWHPFX','CLEAN_SAFE_HOTELS'))
print("SUCCESS")

SUCCESS

In [88]:
from importlib import import_module

named_libs = [('pandas', 'pd')] # (library_name, shorthand)
for (name, short) in named_libs:
    try:
        lib = import_module(name)
    except:
        print(sys.exc_info())
    else:
        globals()[short] = lib  

libnames = ['requests', 'json', 'pyexasol', 'configparser']
for libname in libnames:
    try:
        lib = import_module(libname)
    except:
        print(sys.exc_info())
    else:
        globals()[libname] = lib
        
### API EXTRACTION

def cleanNsafeExtract():
    try:
        ### Initialize the dataframe
        final_df = pd.DataFrame()
        ### API link
        url = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=1&size=100"
        parsed = json.loads(requests.get(url).text)
        ### Get the number of pages through -> #int(parsed['total_pages'])
        for x in range(int(parsed['total_pages'])):
            url_iter = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page="+str(x+1)+"&size=100"
            response = requests.get(url_iter)
            if response.status_code == 200:    
                data = response.text
                parsed = json.loads(data)
                df = pd.DataFrame(parsed.get('results'))
                final_df = final_df.append(df, ignore_index=True)
            else: 
                print("Request failed page: {} ".format(x))
                
        final_df['created_date']= pd.to_datetime(final_df['created_date'])
        final_df['updated_date']= pd.to_datetime(final_df['updated_date'])
        harmonized_df = final_df[final_df.hkey.notnull()]
        harmonized_df = harmonized_df.loc[:, harmonized_df.columns != 'checked']
    except:
        print('Failed in function cleanNsafe - ')
    return harmonized_df, print(f'Number of records having HOTEL_IDs {final_df.id[final_df.hkey.notnull()].count()}.'), print(f'Number of records with no HOTEL_IDs  {final_df.id[final_df.hkey.isna()].count()}.')

In [90]:
df, a, b = cleanNsafeExtract()
df

Number of records having HOTEL_IDs 12447.
Number of records with no HOTEL_IDs  27.

,id,hkey,name,created_date,updated_date,link,program_name,version,terms,services,...,chain_name,brand_id,brand_name,city_id,city,country_id,country,performance_cluster,status,type
0,0008627a-ae90-493f-8686-5718226b1e56,980958.0,Hanting Suzhou Lingbi County(Domestic Only),2020-07-28 02:08:15+00:00,2020-07-28 02:08:15+00:00,https://www.hotel-audit.hrs.com/group-assessme...,Self Inspected,1,2,"restaurant,breakfast",...,China Lodging Hotels Group Ltd (Huazhu),1330.0,China Lodging Hotels Group Ltd (Huazhu),759518.0,Suzhou (Anhui Province),29.0,"China, P.R.",NaN,True,cleansafe_expert_inspection
1,000d14a8-e880-4e27-97c9-876691093d80,1024092.0,汉庭太原千峰南路酒店(内宾),2020-07-28 02:08:41+00:00,2020-07-28 02:08:41+00:00,https://www.hotel-audit.hrs.com/group-assessme...,Self Inspected,1,2,"restaurant,breakfast",...,China Lodging Hotels Group Ltd (Huazhu),1330.0,China Lodging Hotels Group Ltd (Huazhu),49242.0,Taiyuan (Shanxi Province),29.0,"China, P.R.",NaN,True,cleansafe_expert_inspection
2,0013d6a8-41ac-492b-bed6-b0007779edee,980906.0,Hi Inn Nanjing South Station(Domestic Only),2020-07-28 02:08:15+00:00,2020-07-28 02:08:15+00:00,https://www.hotel-audit.hrs.com/group-assessme...,Self Inspected,1,2,"restaurant,breakfast",...,China Lodging Hotels Group Ltd (Huazhu),2152.0,Hi Inn,137271.0,Nanjing (Jiangsu Province),29.0,"China, P.R.",NaN,True,cleansafe_expert_inspection
3,001e3456-3d38-430b-bd30-aae591857c6b,1017263.0,Hanting Luoyang Longmen Railway Station (Domes...,2020-07-28 02:08:31+00:00,2020-07-28 02:08:31+00:00,https://www.hotel-audit.hrs.com/group-assessme...,Self Inspected,1,2,"restaurant,breakfast",...,China Lodging Hotels Group Ltd (Huazhu),1330.0,China Lodging Hotels Group Ltd (Huazhu),135900.0,Luoyang (Henan Province),29.0,"China, P.R.",NaN,True,cleansafe_expert_inspection
4,0026579c-66c4-4845-b280-d7435ec627b8,260487.0,Castle Arch,2020-07-17 12:47:52+00:00,2020-07-17 12:47:52+00:00,https://www.castlearchhotel.com/stay-safe-at-t...,Failte Ireland Covid 19 Safety charter,1,2,"breakfast,restaurant,mice",...,Magnuson Group,1988.0,Magnuson Group,3070924.0,Meath (Meath),62.0,Ireland,5.0,True,cleansafe_self_inspection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12469,ffea3c2b-d742-4d1b-bbca-48125b0a3a4b,664800.0,Hanting Hotel Fuan Bus station,2020-07-28 02:08:00+00:00,2020-07-28 02:08:00+00:00,https://www.hotel-audit.hrs.com/group-assessme...,Self Inspected,1,2,"restaurant,breakfast",...,China Lodging Hotels Group Ltd (Huazhu),1330.0,China Lodging Hotels Group Ltd (Huazhu),245206.0,Ningde (Fujian Province),29.0,"China, P.R.",NaN,True,cleansafe_expert_inspection
12470,ffefc64b-36b0-4ee7-854a-3885ff1de4ce,23658.0,Savoy,2020-06-24 08:22:03+00:00,2020-06-24 08:28:40+00:00,https://www.savoy.it/documents/COVID-Actionpla...,COVID-19 Emergency Management Action Plan,1,2,"breakfast,restaurant,mice",...,individual,-1.0,n.a.,54084.0,Rome (Lazio),65.0,Italy,2.0,True,cleansafe_expert_inspection
12471,ffefe3ae-aedc-46ad-8178-7abf03c5595e,25994.0,Am Neutor Hotel Salzburg Zentrum,2020-07-09 19:08:55+00:00,2020-07-09 19:08:55+00:00,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,breakfast,...,individual,-1.0,n.a.,54723.0,Salzburg (Salzburg),114.0,Austria,3.0,False,cleansafe_self_inspection
12472,fff82fb5-cf9d-4f28-9552-65d9254d3809,74850.0,Hoftaferne Neuburg am Inn,2020-07-09 15:07:38+00:00,2020-07-09 15:07:38+00:00,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,"breakfast,restaurant,mice",...,individual,-1.0,n.a.,127685.0,Neuburg am Inn (Bayern),33.0,Germany,3.0,True,cleansafe_self_inspection
12473,ffffc417-abce-46ae-a2b3-16f4f13d8cd0,634583.0,JI Hotel Xue Yuan Qiao,2020-07-28 02:08:00+00:00,2020-07-28 02:08:00+00:00,https://www.hotel-audit.hrs.com/group-assessme...,Self Inspected,1,2,"restaurant,breakfast",...,China Lodging Hotels Group Ltd (Huazhu),2150.0,JI Hotels,48979.0,Beijing (Beijing Municipality),29.0,"China, P.R.",NaN,True,cleansafe_expert_inspection

In [86]:
def cleanNsafeLoad(df): 
    try:
        #Location of the ini file
        config = configparser.ConfigParser()
        config.read('C:\\Users\\svi02\\.spyder-py3\\pfxIUT.ini')
        dsn=config['pfxIUT']['dsn']
        user=config['pfxIUT']['user']
        pwd=config['pfxIUT']['pwd']
        schema=config['pfxIUT']['schema']
        # Exasol connection
        connect = pyexasol.connect(dsn=dsn, user=user, password=pwd, schema=schema)
        connect.execute("TRUNCATE TABLE DWHPFX.CLEAN_SAFE_HOTELS")
        connect.import_from_pandas(harmonized_df, table = ('DWHPFX','CLEAN_SAFE_HOTELS'))
        print("SUCCESS")
    except:
        print('Failed in function cleanNsafeLoad - check DB connection')
    return print(f'Number of records inserted  {harmonized_df.id[harmonized_df.hkey.notnull()].count()}.')

In [87]:
cleanNsafeLoad(harmonized_df)

SUCCESS
Number of records inserted  6924.

In [79]:
from urllib.parse import urlsplit
parsed = urlsplit("https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=1&size=100")
print('query  :', parsed.query)

query  : secretKey=3AwuZKz9nH&page=1&size=100

In [80]:
print('query  :', parsed.fragment)

query  :

In [148]:
test = harmonized_df[harmonized_df.missed != ""].reset_index()
test.head()

,index,id,hkey,name,created_date,updated_date,link,program_name,version,terms,...,brand_name,city_id,city,country_id,country,performance_cluster,status,type,missed,checked_id
0,13,002fed63-5e6e-47b8-b6fc-3190ff065520,257020.0,Relais Villa Roncuzzi,2020-07-09 17:45:42+00:00,2020-07-09 17:45:42+00:00,https://www.villaroncuzzi.it/progetto-anticovid/,"programma di soggiorno ""sicuricomeacasa""",1,2,...,n.a.,213680.0,Russi (Emilia Romagna),65.0,Italy,4.0,False,cleansafe_self_inspection,"36,36","1,2,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,19,..."
1,26,004e5f32-506a-4896-ab16-ae97d998591e,874980.0,Rosewood Phnom Penh,2020-07-31 17:07:06+00:00,2020-07-31 17:07:06+00:00,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,Rosewood Hotels & Resorts,55033.0,Phnom Penh,74.0,Cambodia,4.0,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4...",None
2,30,0056a799-d418-4c47-9f68-2376dd8b37a3,1046034.0,Via Veneto Prestige Rooms,2020-07-23 11:11:41+00:00,2020-07-23 11:11:41+00:00,https://www.confindustriafirenze.it/covid-19-n...,Protocollo accoglienza sicura,1,2,...,n.a.,54084.0,Rome (Lazio),65.0,Italy,NaN,False,cleansafe_self_inspection,"35,36,37","1,2,3,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,1..."
3,50,0093ffeb-57b4-40c9-9a32-9f4e4faea64d,728.0,DAN PANORAMA HAIFA,2020-07-16 08:59:47+00:00,2020-07-16 08:59:47+00:00,https://www.danhotels.com/AboutDanhotels/News/...,"Dan hotels ""Stay safe & enjoy"" statement",1,2,...,Dan Hotel Group-> Israel Leading Hotels,94242.0,Haifa (H̱efa),64.0,Israel,2.0,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4...",
4,58,00b3f8a1-943e-4c55-adcd-c444b5258664,393711.0,Meliá Desert Palm Dubai,2020-07-30 11:58:45+00:00,2020-07-30 11:58:45+00:00,https://media.melia.com/covid-19/covid_en.html,Stay Safe with Melia,1,2,...,Melia Hotels International,6879.0,Dubai (Dubai),164.0,United Arab Emirates,NaN,False,cleansafe_self_inspection,26,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4..."

In [97]:
#test['missed_desc'] = test['missed'].replace({1:'Public health authorities guidelines', 2:'Risk assessment', 36:'Dish washing machine'})
test['missed_desc'] = test['missed'].str.replace('1','Public health authorities guidelines')
test['missed_desc'] = test['missed'].str.replace('2', 'Risk assessment')
#test['missed_desc'] = test['missed'].str.replace('36','Dish washing machine')
test['missed_desc']

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

13                                                   36,36
26       1,Risk assessment,4,5,6,8,10,11,1Risk assessme...
30                                                35,36,37
50       1,Risk assessment,4,5,6,8,10,11,1Risk assessme...
58                                        Risk assessment6
                               ...
21248    1,Risk assessment,4,5,6,8,10,11,1Risk assessme...
21257    1,Risk assessment,4,5,11,1Risk assessment,Risk...
21258                                                36,37
21262                                     Risk assessment6
21276               Risk assessment,11,1Risk assessment,18
Name: missed_desc, Length: 2318, dtype: object

In [77]:
for row in test.itertuples(name='missed'): 
    #print(row.missed) ##str
    temp = row.missed.split(',')
    print(temp)  ## list with string values

['36', '36']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['35', '36', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['19']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11', '41', '33', '34']
['26']
['5', '11', '27', '28', '39', '40', '42', '32', '34', '37', '37']
['5', '11', '41', '33', '34']
['5', '11', '28']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['2', '12']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['11', '15', '28', '32', '34', '26', '26']
['33']
['33']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['35', '36', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11', '41']
['2', '4', '5', '11', '12', '28', '40']
['5', '11', '27', '28', '39', '40', '42', '32', '34', '37', '37']
['8', '11', '26']
['26']
['11', '12']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['12']
['32', '33']
['2', '5', '8', '11', '15', '18', '27', '28', '36', '37', '32', '36', '37', '26', '44', '46']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['5', '11', '27', '28', '39', '40', '42', '32', '34', '37', '37']
['5', '11', '32']
['27', '28', '25']
['26']
['11']
['5', '6', '12']
['15']
['42']
['46']
['42', '33', '46']
['11']
['1', '4', '5', '11', '15', '28', '41', '32', '33', '34']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['11']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11', '27', '28', '39', '40', '42', '32', '34', '37', '37']
['1', '2', '5', '11', '27', '28', '40']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11', '41', '33', '34', '44', '46']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['5', '27', '28', '34', '46']
['26']
['2', '4', '5', '12', '14', '27', '28', '40', '26']
['26']
['37', '37']
['5', '27', '28', '34', '46']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['42']
['14', '15']
['11', '27', '32']
['5', '8', '18', '28', '36', '37', '32', '33', '34', '36', '37']
['26']
['1', '2', '4', '5', '6', '12', '15', '18', '28', '40']
['28']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['28']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '8', '11', '12', '15', '19', '40']
['8', '27', '35']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['8', '12', '27', '28', '33']
['28', '33']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11', '41', '33', '34', '44', '46']
['11']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['11', '12', '27', '28']
['12', '35', '34', '35']
['5', '15']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42', '32', '33']
['11']
['1', '2', '4', '5', '6', '8', '10', '11', '18', '19', '27', '28', '40', '41', '42', '32', '33', '34']
['5', '18']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '5', '18', '27']
['26']
['1', '4', '5', '8', '10', '11', '12', '28', '42', '26', '26']
['2', '11', '12']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '6', '11', '27', '28', '42', '32', '33', '44']
['36', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '12', '28', '40']
['1', '4', '5', '11', '12']
['5', '11', '12', '27', '28', '42']
['5', '11', '12', '28']
['34']
['28']
['1', '5', '28']
['5', '27']
['1', '2', '4', '5', '11', '12', '15']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['37', '37']
['5', '27', '35', '37']
['5', '10', '11']
['11']
['15']
['28']
['11']
['36']
['26']
['5', '11']
['1', '27', '25', '26']
['33']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '15']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['1', '5', '11', '12', '28']
['5', '8', '11', '15', '28']
['26']
['1']
['11', '27', '28', '26', '25', '26']
['5', '11', '12']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['26']
['5']
['39']
['5', '11', '32', '33']
['5', '6', '12', '15', '33']
['26']
['5', '28', '42', '32', '44']
['5', '11', '12', '40', '35']
['1', '4', '5', '8', '10', '11', '12', '28', '42', '26', '26']
['11']
['5', '8', '11', '26']
['2', '5']
['11', '28', '32', '33']
['2', '5', '11']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11', '41', '33', '34', '44', '46']
['5', '11', '27', '28', '39', '40', '42', '32', '34', '37', '37']
['5', '27', '28', '34', '46']
['5', '10', '11', '12', '28', '40']
['2', '12', '14', '15', '28', '40']
['1', '2', '4', '5', '6', '11', '12', '14', '18', '27', '28', '41', '42', '32', '44', '46']
['27', '28', '36', '36', '26']
['33', '36', '37', '36', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['12']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['28']
['11']
['28', '32', '33', '34']
['2', '5', '12', '28']
['2', '4', '5', '12', '28', '33', '34']
['5', '12', '28']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['2', '5', '11', '12', '18', '27', '28', '35', '35']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['11']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['19', '27', '28', '36', '37', '32', '36', '37', '26']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11', '12', '15']
['11']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['2', '4', '5', '6', '8', '10', '11', '12', '18', '28', '40', '41', '42', '33', '34']
['1', '11']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['44']
['26']
['28', '34']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['4', '5', '6', '11']
['12']
['28']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['26']
['5', '11', '12']
['5']
['11']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['11']
['2', '35', '36', '37']
['42']
['2', '39', '40', '41', '42', '44']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11', '12', '40', '35', '36', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '18', '19', '27', '28', '40', '41', '42']
['11']
['28', '35', '36', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['11', '42']
['26']
['12']
['5', '27', '28', '34']
['44', '46']
['28']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '4', '5', '8', '10', '11', '12', '28', '42', '26', '26']
['5', '6', '11', '28', '40', '41', '33']
['26']
['26']
['15']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11']
['5', '28']
['11', '12', '27', '28', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '18', '28', '42']
['26']
['5', '28', '35', '36', '37']
['44', '46']
['11', '15', '32', '33', '34']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '11', '12', '14', '15', '18', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['5', '11', '41', '33', '34', '44', '46']
['27', '26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['28']
['5', '11', '41']
['5', '11', '41', '33', '34', '44', '46']
['5', '11', '27', '28', '39', '40', '42', '32', '34', '37', '37']
['33']
['4', '5', '11', '12', '27', '28']
['4', '11', '12', '28', '42']
['11']
['11']
['8', '15', '35']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['11', '12', '15', '28']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '11', '12', '14', '15', '19', '28', '40', '41']
['11', '28', '42', '32']
['5', '19', '35', '36', '37', '32', '33', '34', '35', '36', '37', '44', '46']
['5', '12', '42']
['6', '8', '11', '15', '28']
['5', '11', '27', '28', '39', '40', '42', '32', '34', '37', '37']
['1', '2', '28', '32']
['5', '11', '28', '36', '34', '36']
['2', '4', '5', '6', '8', '10', '11', '12', '15', '18', '40', '42', '37']
['1', '2', '4', '5', '27']
['40']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['12', '28']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['26']
['37', '33', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['4', '28', '39', '40', '32', '34']
['1', '2', '5', '12', '14', '19', '39', '40']
['4', '5', '11', '12', '27', '28', '40', '42', '34']
['11', '26']
['36', '37']
['2', '4', '12', '14', '18', '27', '39', '40', '42', '33', '34']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '18', '19', '27', '28', '35', '36', '37', '32', '33', '34', '35', '36', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['33']
['11', '12', '15', '27', '28', '41', '25', '26']
['1', '4', '5', '27', '28', '40']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['44']
['33']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '28', '40', '32']
['2', '4', '5', '6', '8', '11', '18', '28', '40']
['11']
['2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '36', '37', '25', '26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['27']
['2', '8', '12', '33', '25', '26']
['42', '36', '33', '34', '36']
['15']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['11', '12', '14', '15', '18', '19', '27', '28', '35', '36', '37', '25', '26']
['26']
['8', '11', '12', '36', '37']
['12']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '8', '11', '14', '15', '27', '28', '40', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '28', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['28']
['5', '11', '41', '33', '34', '44', '46']
['5', '39', '42']
['5', '11', '41', '33', '34', '44', '46']
['11', '12', '18', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['32']
['11']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '28']
['2', '4', '5', '6', '8', '10', '11', '12', '15', '18', '27', '28', '40', '41', '42', '35', '36', '37']
['2', '28']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11']
['15']
['5', '12', '34']
['5', '11', '41', '33', '34']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['37']
['5', '8', '10', '11']
['1', '2', '4', '5', '11', '12', '19', '28', '40', '42', '32', '34']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['2', '4', '11', '32']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['11']
['5', '11', '27', '28', '39', '40', '42', '32', '34', '37', '37']
['10', '12', '14', '28']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['2', '4', '5', '8', '10', '11', '12', '14', '15', '18', '19', '28', '40', '41', '42', '35', '36', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['32', '33']
['33']
['4', '11', '27', '28', '35', '32', '33', '34', '35']
['14', '18', '28']
['11']
['11']
['5', '18']
['28']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '5', '11', '28', '40']
['1', '2', '4', '5', '11', '15']
['11']
['1', '5', '12', '40', '41']
['11']
['11', '28', '33', '34']
['2', '6', '8', '11', '28']
['26']
['27', '28', '33']
['26']
['2', '11', '42', '26', '26', '44']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['33']
['5', '26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '28', '42']
['11']
['5', '33']
['35', '36', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '12']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['33']
['1', '4', '5', '6', '12', '14', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11', '32', '33']
['37', '37']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '11', '28']
['5', '11', '12', '15', '28']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['11', '28']
['1', '2', '4', '5', '8', '10', '11', '12', '27', '28', '40', '41', '36', '37']
['5', '11', '27', '28', '39', '40', '42', '32', '34', '37', '37']
['15', '40']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['26']
['1', '4', '12']
['11']
['33', '36', '37', '36', '37']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['28']
['26']
['5', '11', '28']
['26']
['5', '11', '41', '33', '34', '44', '46']
['4', '8', '11', '12', '19']
['44']
['5', '11', '41', '33', '34', '44', '46']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['11']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['14']
['11']
['1', '2', '4', '5', '6', '11', '12', '14', '15', '28']
['26']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['5', '27', '33']
['1', '2', '4', '5', '11', '28', '40']
['28', '32']
['8', '11']
['5', '11']
['27', '26']
['5', '11', '15', '32']
['33']
['27', '28', '35']
['28']
['1', '2', '4', '5', '11', '12', '27', '28', '40', '41']
['1', '2', '4', '5', '6', '11', '12', '15', '18', '19', '27', '28', '32', '33', '34']
['1', '2', '4', '5', '6', '8', '10', '11', '12', '14', '15', '18', '19', '27', '28', '39', '40', '41', '42']
['1', '4', '5', '8', '10', '12', '14', '18', '27', '28', '40', '32', '33', '34']
['26']
['1', '2', '5', '8', '10', '12', '14', '15', '39', '40', '41']
['4', '5', '6', '12', '14', '15', '18']
['26']
['1', '5', '11', '12', '36']

In [149]:
test = test.head(5)
test

,index,id,hkey,name,created_date,updated_date,link,program_name,version,terms,...,brand_name,city_id,city,country_id,country,performance_cluster,status,type,missed,checked_id
0,13,002fed63-5e6e-47b8-b6fc-3190ff065520,257020.0,Relais Villa Roncuzzi,2020-07-09 17:45:42+00:00,2020-07-09 17:45:42+00:00,https://www.villaroncuzzi.it/progetto-anticovid/,"programma di soggiorno ""sicuricomeacasa""",1,2,...,n.a.,213680.0,Russi (Emilia Romagna),65.0,Italy,4.0,False,cleansafe_self_inspection,"36,36","1,2,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,19,..."
1,26,004e5f32-506a-4896-ab16-ae97d998591e,874980.0,Rosewood Phnom Penh,2020-07-31 17:07:06+00:00,2020-07-31 17:07:06+00:00,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,Rosewood Hotels & Resorts,55033.0,Phnom Penh,74.0,Cambodia,4.0,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4...",None
2,30,0056a799-d418-4c47-9f68-2376dd8b37a3,1046034.0,Via Veneto Prestige Rooms,2020-07-23 11:11:41+00:00,2020-07-23 11:11:41+00:00,https://www.confindustriafirenze.it/covid-19-n...,Protocollo accoglienza sicura,1,2,...,n.a.,54084.0,Rome (Lazio),65.0,Italy,NaN,False,cleansafe_self_inspection,"35,36,37","1,2,3,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,1..."
3,50,0093ffeb-57b4-40c9-9a32-9f4e4faea64d,728.0,DAN PANORAMA HAIFA,2020-07-16 08:59:47+00:00,2020-07-16 08:59:47+00:00,https://www.danhotels.com/AboutDanhotels/News/...,"Dan hotels ""Stay safe & enjoy"" statement",1,2,...,Dan Hotel Group-> Israel Leading Hotels,94242.0,Haifa (H̱efa),64.0,Israel,2.0,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4...",
4,58,00b3f8a1-943e-4c55-adcd-c444b5258664,393711.0,Meliá Desert Palm Dubai,2020-07-30 11:58:45+00:00,2020-07-30 11:58:45+00:00,https://media.melia.com/covid-19/covid_en.html,Stay Safe with Melia,1,2,...,Melia Hotels International,6879.0,Dubai (Dubai),164.0,United Arab Emirates,NaN,False,cleansafe_self_inspection,26,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4..."

In [138]:
missed_desc = []
for row in test.itertuples(name='missed'): 
    #print(row.missed) ##str
    temp = row.missed.split(',')
    #print(temp)  ## list with string values
    for i in range(len(temp)):
        #temp_desc = temp.replace({"1":"Public health authorities guidelines", "2":"Risk assessment"}).copy()
        if temp[i] == '1':
            temp[i] = "Public health authorities guidelines"
        elif temp[i] == '2':
            temp[i] = "Risk assessment"
        elif temp[i] == '3':
            temp[i] = "Risk assessment - hotel staff"
        elif temp[i] == '4':
            temp[i] = "Action plan"
        elif temp[i] == '5':
            temp[i] = "Log books"
        elif temp[i] == '6':
            temp[i] = "Staff/Guests well informed"
        elif temp[i] == '7':
            temp[i] = "Staff/Guests assessed"
        elif temp[i] == '8':
            temp[i] = "Pictograms"
        elif temp[i] == '9':
            temp[i] = "Updated contact info"
        elif temp[i] == '10':
            temp[i] = "Staff training"
        elif temp[i] == '11':
            temp[i] = "Tracing system"
        elif temp[i] == '12':
            temp[i] = "Hygiene - suppliers/contractors"
        elif temp[i] == '13':
            temp[i] = "Web checkin"
        elif temp[i] == '14':
            temp[i] = "Hotel hygiene - guests"
        elif temp[i] == '15':
            temp[i] = "Common area- social distancing"
        elif temp[i] == '16':
            temp[i] = "PPE/kits - staff"
        elif temp[i] == '17':
            temp[i] = "PPE/kits - guests"
        elif temp[i] == '18':
            temp[i] = "Staff remind guests"
        elif temp[i] == '19':
            temp[i] = "Disinfectant - room keys"
        elif temp[i] == '20':
            temp[i] = "Disinfected pools"
        elif temp[i] == '21':
            temp[i] = "Lockers - Spa/fitness social distancing"
        elif temp[i] == '22':
            temp[i] = "Lockers - Spa/fitness"
        elif temp[i] == '23':
            temp[i] = "Disinfectant products - fitness"
        elif temp[i] == '24':
            temp[i] = "Disinfectant reminder - fitness"
        elif temp[i] == '25':
            temp[i] = "Fitness equipment"
        elif temp[i] == '26':
            temp[i] = "Social distancing - Spa/fitness"
        elif temp[i] == '27':
            temp[i] = "Dish washers and washing machine"
        elif temp[i] == '28':
            temp[i] = "HVAC systems"
        elif temp[i] == '29':
            temp[i] = "Sanitiser dispensers"
        elif temp[i] == '30':
            temp[i] = "Public restrooms"
        elif temp[i] == '31':
            temp[i] = "Take away/Room service"
        elif temp[i] == '32':
            temp[i] = "Safety measures - buffets"
        elif temp[i] == '33':
            temp[i] = "Disinfection - buffet areas"
        elif temp[i] == '34':
            temp[i] = "Disinfection - vending machines"
        elif temp[i] == '35':
            temp[i] = "Dishwashing machine"
        elif temp[i] == '36':
            temp[i] = "Social distancing dining"
        elif temp[i] == '37':
            temp[i] = "Social distancing seating"
        elif temp[i] == '38':
            temp[i] = "Guest reminder"
        elif temp[i] == '39':
            temp[i] = "Cleaning protocol - public areas"
        elif temp[i] == '40':
            temp[i] = "Disinfection protocol - COVID cases"
        elif temp[i] == '41':
            temp[i] = "Disinfection - guest rooms"
        elif temp[i] == '42':
            temp[i] = "Dirty linen storage"
        elif temp[i] == '43':
            temp[i] = "Ventilation"
        elif temp[i] == '44':
            temp[i] = "Staff to access meeting room"
        elif temp[i] == '45':
            temp[i] = "Luggage store for group"
        elif temp[i] == '46':
            temp[i] = "Social distancing - meeting rooms"
    missed_desc.append(temp)
missed_desc

[['Social distancing dining', 'Social distancing dining'],
 ['Public health authorities guidelines',
  'Risk assessment',
  'Action plan',
  'Log books',
  'Staff/Guests well informed',
  'Pictograms',
  'Staff training',
  'Tracing system',
  'Hygiene - suppliers/contractors',
  'Hotel hygiene - guests',
  'Common area- social distancing',
  'Staff remind guests',
  'Disinfectant - room keys',
  'Dish washers and washing machine',
  'HVAC systems',
  'Cleaning protocol - public areas',
  'Disinfection protocol - COVID cases',
  'Disinfection - guest rooms',
  'Dirty linen storage'],
 ['Dishwashing machine',
  'Social distancing dining',
  'Social distancing seating'],
 ['Public health authorities guidelines',
  'Risk assessment',
  'Action plan',
  'Log books',
  'Staff/Guests well informed',
  'Pictograms',
  'Staff training',
  'Tracing system',
  'Hygiene - suppliers/contractors',
  'Hotel hygiene - guests',
  'Common area- social distancing',
  'Staff remind guests',
  'Disinfectant - room keys',
  'Dish washers and washing machine',
  'HVAC systems',
  'Cleaning protocol - public areas',
  'Disinfection protocol - COVID cases',
  'Disinfection - guest rooms',
  'Dirty linen storage'],
 ['Social distancing - Spa/fitness']]

In [141]:
test1 = [str(item) for item in missed_desc]
# test1
missed_df = pd.DataFrame(test1)
missed_df

                                                   0
0  ['Social distancing dining', 'Social distancin...
1  ['Public health authorities guidelines', 'Risk...
2  ['Dishwashing machine', 'Social distancing din...
3  ['Public health authorities guidelines', 'Risk...
4                ['Social distancing - Spa/fitness']

In [150]:
test = test.join(missed_df)

In [151]:
test #257020, 874980, 728

,index,id,hkey,name,created_date,updated_date,link,program_name,version,terms,...,city_id,city,country_id,country,performance_cluster,status,type,missed,checked_id,0
0,13,002fed63-5e6e-47b8-b6fc-3190ff065520,257020.0,Relais Villa Roncuzzi,2020-07-09 17:45:42+00:00,2020-07-09 17:45:42+00:00,https://www.villaroncuzzi.it/progetto-anticovid/,"programma di soggiorno ""sicuricomeacasa""",1,2,...,213680.0,Russi (Emilia Romagna),65.0,Italy,4.0,False,cleansafe_self_inspection,"36,36","1,2,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,19,...","['Social distancing dining', 'Social distancin..."
1,26,004e5f32-506a-4896-ab16-ae97d998591e,874980.0,Rosewood Phnom Penh,2020-07-31 17:07:06+00:00,2020-07-31 17:07:06+00:00,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,55033.0,Phnom Penh,74.0,Cambodia,4.0,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4...",None,"['Public health authorities guidelines', 'Risk..."
2,30,0056a799-d418-4c47-9f68-2376dd8b37a3,1046034.0,Via Veneto Prestige Rooms,2020-07-23 11:11:41+00:00,2020-07-23 11:11:41+00:00,https://www.confindustriafirenze.it/covid-19-n...,Protocollo accoglienza sicura,1,2,...,54084.0,Rome (Lazio),65.0,Italy,NaN,False,cleansafe_self_inspection,"35,36,37","1,2,3,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,1...","['Dishwashing machine', 'Social distancing din..."
3,50,0093ffeb-57b4-40c9-9a32-9f4e4faea64d,728.0,DAN PANORAMA HAIFA,2020-07-16 08:59:47+00:00,2020-07-16 08:59:47+00:00,https://www.danhotels.com/AboutDanhotels/News/...,"Dan hotels ""Stay safe & enjoy"" statement",1,2,...,94242.0,Haifa (H̱efa),64.0,Israel,2.0,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4...",,"['Public health authorities guidelines', 'Risk..."
4,58,00b3f8a1-943e-4c55-adcd-c444b5258664,393711.0,Meliá Desert Palm Dubai,2020-07-30 11:58:45+00:00,2020-07-30 11:58:45+00:00,https://media.melia.com/covid-19/covid_en.html,Stay Safe with Melia,1,2,...,6879.0,Dubai (Dubai),164.0,United Arab Emirates,NaN,False,cleansafe_self_inspection,26,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4...",['Social distancing - Spa/fitness']

In [184]:
# import datetime as dt
### Initialize the dataframe
final_df = pd.DataFrame()
### API link
url = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=1&size=100"
parsed = json.loads(requests.get(url).text)
### Get the number of pages through -> #int(parsed['total_pages'])
for x in range(int(parsed['total_pages'])):
    url_iter = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page="+str(x+1)+"&size=100"
    response = requests.get(url_iter)
    if response.status_code == 200:    
        data = response.text
        parsed = json.loads(data)
        df = pd.DataFrame(parsed.get('results'))
        final_df = final_df.append(df, ignore_index=True)
    else: 
        print("Request failed page: {} ".format(x))

#         final_df['created_date']= pd.to_datetime(final_df['created_date'])
#         final_df['updated_date']= pd.to_datetime(final_df['updated_date'])
final_df['created_date']= final_df['created_date'].dt.tz_localize(None)
final_df['updated_date']= final_df['updated_date'].dt.tz_localize(None)
harmonized_df = final_df[final_df.hkey.notnull()]
#harmonized_df = harmonized_df.loc[:, harmonized_df.columns != 'checked']
missed_desc = []
for row in harmonized_df.itertuples(name='missed'): 
    #print(row.missed) ##str
    temp = row.missed.split(',')
    #print(temp)  ## list with string values
    for i in range(len(temp)):
        #temp_desc = temp.replace({"1":"Public health authorities guidelines", "2":"Risk assessment"}).copy()
        if temp[i] == '1':
            temp[i] = "Public health authorities guidelines"
        elif temp[i] == '2':
            temp[i] = "Risk assessment"
        elif temp[i] == '3':
            temp[i] = "Risk assessment - hotel staff"
        elif temp[i] == '4':
            temp[i] = "Action plan"
        elif temp[i] == '5':
            temp[i] = "Log books"
        elif temp[i] == '6':
            temp[i] = "Staff/Guests well informed"
        elif temp[i] == '7':
            temp[i] = "Staff/Guests assessed"
        elif temp[i] == '8':
            temp[i] = "Pictograms"
        elif temp[i] == '9':
            temp[i] = "Updated contact info"
        elif temp[i] == '10':
            temp[i] = "Staff training"
        elif temp[i] == '11':
            temp[i] = "Tracing system"
        elif temp[i] == '12':
            temp[i] = "Hygiene - suppliers/contractors"
        elif temp[i] == '13':
            temp[i] = "Web checkin"
        elif temp[i] == '14':
            temp[i] = "Hotel hygiene - guests"
        elif temp[i] == '15':
            temp[i] = "Common area- social distancing"
        elif temp[i] == '16':
            temp[i] = "PPE/kits - staff"
        elif temp[i] == '17':
            temp[i] = "PPE/kits - guests"
        elif temp[i] == '18':
            temp[i] = "Staff remind guests"
        elif temp[i] == '19':
            temp[i] = "Disinfectant - room keys"
        elif temp[i] == '20':
            temp[i] = "Disinfected pools"
        elif temp[i] == '21':
            temp[i] = "Lockers - Spa/fitness social distancing"
        elif temp[i] == '22':
            temp[i] = "Lockers - Spa/fitness"
        elif temp[i] == '23':
            temp[i] = "Disinfectant products - fitness"
        elif temp[i] == '24':
            temp[i] = "Disinfectant reminder - fitness"
        elif temp[i] == '25':
            temp[i] = "Fitness equipment"
        elif temp[i] == '26':
            temp[i] = "Social distancing - Spa/fitness"
        elif temp[i] == '27':
            temp[i] = "Dish washers and washing machine"
        elif temp[i] == '28':
            temp[i] = "HVAC systems"
        elif temp[i] == '29':
            temp[i] = "Sanitiser dispensers"
        elif temp[i] == '30':
            temp[i] = "Public restrooms"
        elif temp[i] == '31':
            temp[i] = "Take away/Room service"
        elif temp[i] == '32':
            temp[i] = "Safety measures - buffets"
        elif temp[i] == '33':
            temp[i] = "Disinfection - buffet areas"
        elif temp[i] == '34':
            temp[i] = "Disinfection - vending machines"
        elif temp[i] == '35':
            temp[i] = "Dishwashing machine"
        elif temp[i] == '36':
            temp[i] = "Social distancing dining"
        elif temp[i] == '37':
            temp[i] = "Social distancing seating"
        elif temp[i] == '38':
            temp[i] = "Guest reminder"
        elif temp[i] == '39':
            temp[i] = "Cleaning protocol - public areas"
        elif temp[i] == '40':
            temp[i] = "Disinfection protocol - COVID cases"
        elif temp[i] == '41':
            temp[i] = "Disinfection - guest rooms"
        elif temp[i] == '42':
            temp[i] = "Dirty linen storage"
        elif temp[i] == '43':
            temp[i] = "Ventilation"
        elif temp[i] == '44':
            temp[i] = "Staff to access meeting room"
        elif temp[i] == '45':
            temp[i] = "Luggage store for group"
        elif temp[i] == '46':
            temp[i] = "Social distancing - meeting rooms"
    missed_desc.append(temp)
missed_desc
temp = [str(item) for item in missed_desc]
missed_df = pd.DataFrame(temp)
harmonized_df = harmonized_df.join(missed_df)
harmonized_df.rename(columns={0: "missed_desc"}, inplace = True)

AttributeError: Can only use .dt accessor with datetimelike values

In [187]:
final_df['created_date'].tz_localize(None)

TypeError: index is not a valid DatetimeIndex or PeriodIndex

In [161]:
harmonized_df[harmonized_df.hkey == 257020]

,id,hkey,name,created_date,updated_date,link,program_name,version,terms,services,...,city_id,city,country_id,country,performance_cluster,status,type,missed,checked_id,0
13,002fed63-5e6e-47b8-b6fc-3190ff065520,257020.0,Relais Villa Roncuzzi,2020-07-09 17:45:42+00:00,2020-07-09 17:45:42+00:00,https://www.villaroncuzzi.it/progetto-anticovid/,"programma di soggiorno ""sicuricomeacasa""",1,2,"breakfast,restaurant",...,213680.0,Russi (Emilia Romagna),65.0,Italy,4.0,False,cleansafe_self_inspection,"36,36","1,2,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,19,...","['Social distancing dining', 'Social distancin..."

In [163]:
harmonized_df.columns

Index([                 'id',                'hkey',                'name',
              'created_date',        'updated_date',                'link',
              'program_name',             'version',               'terms',
                  'services',          'audit_date',             'auditor',
                  'chain_id',          'chain_name',            'brand_id',
                'brand_name',             'city_id',                'city',
                'country_id',             'country', 'performance_cluster',
                    'status',                'type',              'missed',
                'checked_id',                     0],
      dtype='object')

In [164]:
harmonized_df.rename(columns={0: "missed_desc"}, inplace = True)

In [178]:
harmonized_df.loc[harmonized_df.missed_desc.str.len() > 4]

,id,hkey,name,created_date,updated_date,link,program_name,version,terms,services,...,city_id,city,country_id,country,performance_cluster,status,type,missed,checked_id,missed_desc
13,002fed63-5e6e-47b8-b6fc-3190ff065520,257020.0,Relais Villa Roncuzzi,2020-07-09 17:45:42+00:00,2020-07-09 17:45:42+00:00,https://www.villaroncuzzi.it/progetto-anticovid/,"programma di soggiorno ""sicuricomeacasa""",1,2,"breakfast,restaurant",...,213680.0,Russi (Emilia Romagna),65.0,Italy,4.0,False,cleansafe_self_inspection,"36,36","1,2,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,19,...","['Social distancing dining', 'Social distancin..."
26,004e5f32-506a-4896-ab16-ae97d998591e,874980.0,Rosewood Phnom Penh,2020-07-31 17:07:06+00:00,2020-07-31 17:07:06+00:00,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,None,...,55033.0,Phnom Penh,74.0,Cambodia,4.0,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4...",None,"['Public health authorities guidelines', 'Risk..."
30,0056a799-d418-4c47-9f68-2376dd8b37a3,1046034.0,Via Veneto Prestige Rooms,2020-07-23 11:11:41+00:00,2020-07-23 11:11:41+00:00,https://www.confindustriafirenze.it/covid-19-n...,Protocollo accoglienza sicura,1,2,breakfast,...,54084.0,Rome (Lazio),65.0,Italy,NaN,False,cleansafe_self_inspection,"35,36,37","1,2,3,4,5,6,7,8,10,11,12,9,13,14,15,16,17,18,1...","['Dishwashing machine', 'Social distancing din..."
50,0093ffeb-57b4-40c9-9a32-9f4e4faea64d,728.0,DAN PANORAMA HAIFA,2020-07-16 08:59:47+00:00,2020-07-16 08:59:47+00:00,https://www.danhotels.com/AboutDanhotels/News/...,"Dan hotels ""Stay safe & enjoy"" statement",1,2,,...,94242.0,Haifa (H̱efa),64.0,Israel,2.0,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4...",,"['Public health authorities guidelines', 'Risk..."
58,00b3f8a1-943e-4c55-adcd-c444b5258664,393711.0,Meliá Desert Palm Dubai,2020-07-30 11:58:45+00:00,2020-07-30 11:58:45+00:00,https://media.melia.com/covid-19/covid_en.html,Stay Safe with Melia,1,2,"fitness,restaurant,breakfast,mice",...,6879.0,Dubai (Dubai),164.0,United Arab Emirates,NaN,False,cleansafe_self_inspection,26,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4...",['Social distancing - Spa/fitness']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21220,ff24303a-3225-4915-b436-22d5f127469d,962964.0,Homewood Suites Austin Downtown,2020-07-31 16:16:28+00:00,2020-07-31 16:16:28+00:00,https://www.hilton.com/en/corporate/cleanstay/,Hilton CleanStayTM,1,2,None,...,228975.0,Austin (Texas),165.0,USA,5.0,True,cleansafe_expert_inspection,,"1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,19,...","['Public health authorities guidelines', 'Risk..."
21229,ff3f6da6-bb7e-4296-a189-4e3b3e7e9fa4,123660.0,Hampton Inn Santee-I-95,2020-07-31 16:16:20+00:00,2020-07-31 16:16:20+00:00,https://www.hilton.com/en/corporate/cleanstay/,Hilton CleanStayTM,1,2,None,...,199348.0,Santee (South Carolina),165.0,USA,5.0,True,cleansafe_expert_inspection,,"1,2,3,4,5,6,8,10,11,12,13,14,15,16,17,18,19,20...","['Public health authorities guidelines', 'Risk..."
21230,ff3fa2fa-08a9-4a08-8b28-005a75c2f74c,789410.0,CasaSur Palermo Hotel,2020-07-08 16:06:26+00:00,2020-07-08 16:06:26+00:00,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,"breakfast,restaurant",...,142638.0,Vicente López (Provincia de Buenos Aires),9.0,Argentina,5.0,True,cleansafe_self_inspection,,"1,2,3,4,5,6,7,8,10,11,12,9,14,15,16,17,18,19,2...","['Social distancing dining', 'Social distancin..."
21234,ff445b80-cf32-4368-86ed-70e171c41a84,1016865.0,Orange Select Shanghai Zhongshan Park East Chi...,2020-07-28 02:08:26+00:00,2020-07-28 02:08:26+00:00,https://www.hotel-audit.hrs.com/group-assessme...,Self Inspected,1,2,"restaurant,breakfast",...,49184.0,Shanghai (Shanghai Municipality),29.0,"China, P.R.",5.0,True,cleansafe_expert_inspection,,"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,2...",['Social distancing - Spa/fitness']
21248,ff9bef74-85aa-4b4e-837d-f6567fec5c03,962193.0,Villa Monticello Boutique Hotel,2020-07-24 14:41:54+00:00,2020-07-24 14:41:54+00:00,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,None,...,119.0,Accra (Greater Accra Region),46.0,Ghana,NaN,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4...",None,"['Risk assessment', 'Tracing system', 'Hygiene..."

In [176]:
len(harmonized_df.missed_desc) > 4

True

In [7]:
import requests
import json
import pandas as pd

### Initialize the dataframe
final_df = pd.DataFrame()
url_iter = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=1&size=100"
response = requests.get(url_iter)
data = response.text
parsed = json.loads(data)
df = pd.DataFrame(parsed.get('results'))
df
# if response.status_code == 200:    
#     data = response.text
#     parsed = json.loads(data)
#     df = pd.DataFrame(parsed.get('results'))
#     final_df = final_df.append(df, ignore_index=True)
# final_df

,id,hkey,name,created_date,updated_date,checked,link,program_name,version,terms,...,brand_id,brand_name,city_id,city,country_id,country,performance_cluster,status,type,missed
0,00005b15-b99c-444d-97bf-d3cd02f8c8db,431251,Homewood Suites by Hilton Atlanta I-85-Lawrenc...,2020-07-31T16:16:24.000Z,2020-07-31T16:16:24.000Z,"1,2,3,4,5,6,8,10,11,12,13,14,15,16,17,18,19,20...",https://www.hilton.com/en/corporate/cleanstay/,Hilton CleanStayTM,1,2,...,1537,Homewood Suites by Hilton,168172,Lawrenceville (Georgia),165,USA,4.0,True,cleansafe_self_inspection,
1,00016f7b-171e-4be7-900a-5d0f10bd9018,121783,Clarion Hotel Kansas City - Overland Park,2020-08-13T18:49:23.000Z,2020-08-13T18:49:23.000Z,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,32,33,3...",https://www.radissonhotels.com/en-us/social-re...,SGS - 20 & 10 steps Protocols,1,2,...,1094,Radisson Hotel Group (Opt-in 14%),163963,Lenexa (Kansas),165,USA,NaN,True,cleansafe_expert_inspection,
2,0001db0c-cfb3-4c83-b841-67bbf7f002f0,404054,Quality Suites Stratford,2020-09-03T19:39:02.000Z,2020-09-03T19:39:02.000Z,None,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,1760,Quality by Choice,141060,Stratford (Connecticut),165,USA,5.0,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4..."
3,000225aa-e50c-46c0-a3fe-65813215f837,442825,Hampton Inn - Suites Mount Pleasant,2020-07-31T16:16:24.000Z,2020-07-31T16:16:24.000Z,"1,2,3,4,5,6,8,10,11,12,13,14,15,16,17,18,19,20...",https://www.hilton.com/en/corporate/cleanstay/,Hilton CleanStayTM,1,2,...,1535,Hampton Inn by Hilton,190895,Mount Pleasant (Texas),165,USA,5.0,True,cleansafe_self_inspection,
4,000311b7-76c8-46f3-a9d5-9a82cc5b813d,863579,ibis Styles Barcelona City Bogatell,2020-08-28T08:06:14.000Z,2020-08-28T08:06:14.000Z,"1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,2...",https://www.all.accor.com/event/allsafe.en.shtml,ALLSAFE,1,2,...,1602,IBIS Styles Standard,64430,Barcelona (Catalunya),140,Spain,2.0,True,cleansafe_expert_inspection,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0065ac4f-9178-4b50-9ef9-6a0d08afd153,980941,Hanting Jining Jiaxiang Bus Station(Domestic O...,2020-07-28T02:08:15.000Z,2020-07-28T02:08:15.000Z,"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,2...",https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,1330,China Lodging Hotels Group Ltd (Huazhu),758936,Jining (Shandong Province),29,"China, P.R.",NaN,True,cleansafe_self_inspection,
96,0065fd35-bc48-4ade-898d-dfcb040d394d,592877,Hanting Hotel Ming Dynasty Wall East Gate (Dom...,2020-07-28T02:07:56.000Z,2020-07-28T02:07:56.000Z,"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,2...",https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,1330,China Lodging Hotels Group Ltd (Huazhu),29123,Xi'an (Shaanxi Province),29,"China, P.R.",NaN,True,cleansafe_self_inspection,
97,00683a6d-ba0b-482a-930b-a663f881a732,29433,Copthorne Hotel Slough Windsor,2020-07-13T15:28:53.000Z,2020-07-13T15:28:53.000Z,"1,2,3,4,5,6,8,9,10,11,12,14,15,17,18,19,27,28,...",https://www.millenniumhotels.com/en/offers/glo...,"We Clean, We Care, We Welcome by Millennium Ho...",1,2,...,2353,Millenium & Copthorne Hotels EMAE,32643,Slough (England),50,United Kingdom,3.0,True,cleansafe_self_inspection,
98,0068e91a-61d0-4bb6-b58c-37748b2b68e6,132732,Comfort Inn Central University South,2020-09-08T14:14:24.000Z,2020-09-08T14:14:24.000Z,None,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,1758,Comfort Inn by Choice,184699,Ellensburg (Washington),165,USA,5.0,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4..."
99,0069d13f-5ed7-4625-979e-5d62dea8d60a,256801,Homewood Suites by Hilton Louisville-East,2020-07-31T16:16:22.000Z,2020-07-31T16:16:22.000Z,"1,2,3,4,5,6,8,10,11,12,13,14,15,16,17,18,19,20...",https://www.hilton.com/en/corporate/cleanstay/,Hilton CleanStayTM,1,2,...,1537,Homewood Suites by Hilton,3059218,Louisville (Kentucky),165,USA,5.0,True,cleansafe_self_inspection,

In [8]:
parsed['total_pages']

572

In [9]:
### Initialize the dataframe
final_df = pd.DataFrame()
### API link
url = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page=1&size=100"
parsed = json.loads(requests.get(url).text)
### Get the number of pages through -> #int(parsed['total_pages'])
for x in range(5):
    url_iter = "https://api.hotel-audit.hrs.com/v1/audits/report?secretKey=3AwuZKz9nH&page="+str(x+1)+"&size=100"
    response = requests.get(url_iter)
    if response.status_code == 403 or response.status_code == 200:    
        data = response.text
        parsed = json.loads(data)
        df = pd.DataFrame(parsed.get('results'))
        final_df = final_df.append(df, ignore_index=True)
    else: 
        print("Request failed page: {} ".format(x))

final_df['created_date']= pd.to_datetime(final_df['created_date'])
final_df['updated_date']= pd.to_datetime(final_df['updated_date'])
harmonized_df = final_df[final_df.hkey.notnull()]
harmonized_df

,id,hkey,name,created_date,updated_date,checked,link,program_name,version,terms,...,brand_id,brand_name,city_id,city,country_id,country,performance_cluster,status,type,missed
0,00005b15-b99c-444d-97bf-d3cd02f8c8db,431251.0,Homewood Suites by Hilton Atlanta I-85-Lawrenc...,2020-07-31 16:16:24+00:00,2020-07-31 16:16:24+00:00,"1,2,3,4,5,6,8,10,11,12,13,14,15,16,17,18,19,20...",https://www.hilton.com/en/corporate/cleanstay/,Hilton CleanStayTM,1,2,...,1537.0,Homewood Suites by Hilton,168172.0,Lawrenceville (Georgia),165.0,USA,4.0,True,cleansafe_self_inspection,
1,00016f7b-171e-4be7-900a-5d0f10bd9018,121783.0,Clarion Hotel Kansas City - Overland Park,2020-08-13 18:49:23+00:00,2020-08-13 18:49:23+00:00,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,32,33,3...",https://www.radissonhotels.com/en-us/social-re...,SGS - 20 & 10 steps Protocols,1,2,...,1094.0,Radisson Hotel Group (Opt-in 14%),163963.0,Lenexa (Kansas),165.0,USA,NaN,True,cleansafe_expert_inspection,
2,0001db0c-cfb3-4c83-b841-67bbf7f002f0,404054.0,Quality Suites Stratford,2020-09-03 19:39:02+00:00,2020-09-03 19:39:02+00:00,None,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,1760.0,Quality by Choice,141060.0,Stratford (Connecticut),165.0,USA,5.0,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4..."
3,000225aa-e50c-46c0-a3fe-65813215f837,442825.0,Hampton Inn - Suites Mount Pleasant,2020-07-31 16:16:24+00:00,2020-07-31 16:16:24+00:00,"1,2,3,4,5,6,8,10,11,12,13,14,15,16,17,18,19,20...",https://www.hilton.com/en/corporate/cleanstay/,Hilton CleanStayTM,1,2,...,1535.0,Hampton Inn by Hilton,190895.0,Mount Pleasant (Texas),165.0,USA,5.0,True,cleansafe_self_inspection,
4,000311b7-76c8-46f3-a9d5-9a82cc5b813d,863579.0,ibis Styles Barcelona City Bogatell,2020-08-28 08:06:14+00:00,2020-08-28 08:06:14+00:00,"1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,2...",https://www.all.accor.com/event/allsafe.en.shtml,ALLSAFE,1,2,...,1602.0,IBIS Styles Standard,64430.0,Barcelona (Catalunya),140.0,Spain,2.0,True,cleansafe_expert_inspection,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,02040172-06d8-4ce4-b7be-d17c0a40a68b,126281.0,COUNTRY INN AND SUITES BOTHELL,2020-08-13 18:49:23+00:00,2020-08-13 18:49:23+00:00,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,32,33,3...",https://www.radissonhotels.com/en-us/social-re...,SGS - 20 & 10 steps Protocols,1,2,...,1609.0,Radisson Hotel Group (opt-In 15%),246113.0,Bothell (Washington),165.0,USA,5.0,True,cleansafe_expert_inspection,
496,02042e71-31e2-466b-8bcd-3ecf6af2a67f,787279.0,Rodeway Inn Camp Springs,2020-09-03 19:39:05+00:00,2020-09-03 19:39:05+00:00,None,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,1766.0,Rodeway Inn,209634.0,Morningside (Maryland),165.0,USA,NaN,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4..."
497,0204e3f5-5ac1-4ef4-a160-fcc107466ea3,133200.0,Quality Inn and Suites,2020-09-03 22:28:59+00:00,2020-09-03 22:28:59+00:00,None,https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,1760.0,Quality by Choice,829976.0,Escanaba (Michigan),165.0,USA,NaN,False,cleansafe_self_inspection,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,39,40,4..."
498,0205b7ca-d6f7-40d7-a1c9-1b84efa926d3,526455.0,RADISSON BLU BELORUSSKAYA MOW,2020-08-13 18:49:23+00:00,2020-08-13 18:49:23+00:00,"1,2,4,5,6,8,10,11,12,14,15,18,19,27,28,32,33,3...",https://www.radissonhotels.com/en-us/social-re...,SGS - 20 & 10 steps Protocols,1,2,...,1094.0,Radisson Hotel Group (Opt-in 14%),97830.0,Moskva (Moskva),202.0,Russia,2.0,True,cleansafe_expert_inspection,
499,0205e769-b9cb-4e44-82bc-46c3bed8b3ce,826109.0,Hanting Bayi Pavilion,2020-07-28 02:08:05+00:00,2020-07-28 02:08:05+00:00,"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,2...",https://www.hotel-audit.hrs.com/clean-and-safe,Clean & Safe Protocol,1,2,...,1330.0,China Lodging Hotels Group Ltd (Huazhu),137255.0,Nanchang (Jiangxi Province),29.0,"China, P.R.",NaN,True,cleansafe_self_inspection,